### ISSUE TITLE
[BUG] "Last updated" string is not localized with i18n

### ISSUE THREAD

**Issue by vinser** [gethinode/hinode#1004]
## Describe the bug

Docs pages footer string "Last updated" is not localized

## To reproduce

On docs page switch language to other than English

## Expected behavior

Should use i18n <lang>.yaml `id: lastModified` 

## Host environment

 - Hinode version: [v0.24.6]

**Comment by vinser** [comment]
It may be fixed with replacement line 2 in `git.html` 
from
```
Last updated: {{ $lastmodstr }}
```
to
```
{{ $lastmodstr | i18n "lastModified" -}}
```

**Comment by markdumay** [comment]
Thanks for reporting this - I'll release a fix soon.
