### ISSUE TITLE
[BUG] Blockquote rendering is missing the Bootstrap class

### ISSUE THREAD

**Issue by Ipstenu** [gethinode/hinode#1070]
## Describe the bug

When using markdown to create a block quote (i.e. `> this is a quote`) the required formatting class of `blockquote` is not applied. Without this, you just have unformatted paragraphs, because of the `reset.scss` file.

## To reproduce

1. Create a new post with a blockquote (i.e. `> this is a quote`) 
2. View the page source and see `<blockquote>[content]</blockquote>`

## Expected behavior

The output should be `<blockquote class="blockquote">[content]</blockquote>`

## Host environment

Please complete the following information where applicable.

 - Hinode version: v0.25.1
 - Host OS: macOS Sonoma 14.5 (23F79)
 - Node version: node v22.5.1 (npm v10.8.2)
 - Browser: N/A (tested on Safari and Chrome and FireFox)

## Hugo environment

```bash
> @JorjaFox/website@3.0.2 env
> hugo env

hugo v0.131.0-bfbee17932ff24009008aa94cdd75c0c41f59279+extended darwin/arm64 BuildDate=2024-08-02T09:03:48Z VendorInfo=gohugoio
GOOS="darwin"
GOARCH="arm64"
GOVERSION="go1.22.5"
OptionParser::InvalidOption: invalid option: --embedded
  Use --trace for backtrace.
github.com/sass/libsass="3.6.5"
github.com/webmproject/libwebp="v1.3.2"
```

## Additional context

I tried using [Markdown Attributes](https://gohugo.io/content-management/markdown-attributes/) like this:

```
> This is a blockquote.
{class="bootstrap" hidden=hidden}
```

But even with parser set up properly, it wouldn't work.

I ended up making a shortcode so I could apply citations and authors of quotes:

```
<figure>
  <blockquote class="blockquote">
    {{ .Inner | .Page.RenderString }}
    {{ if .Get "by" }}
      <figcaption class="blockquote-footer">
        {{ if .Get "source" }}
          <cite title='{{ .Get "source" }}'><a href='{{ .Get "source" }}'>{{ .Get "by" }}</a></cite>
        {{ else }}
            {{ .Get "by" }}
        {{ end}}
    </figcaption>
    {{ end }}
  </blockquote>
</figure>
```

Which works as:

```
{{< blockquote by="Joan Jett">}}
I love rock 'n' roll
So put another dime in the jukebox, baby
{{< /blockquote }}
```

The code for this site is at https://github.com/JorjaFox/website/tree/blog-posts-import (the branch is where I'm currently doing a lot of ugly manual work to migrate data selectively from a very old WP site)

**Comment by markdumay** [comment]
Thanks for your elaborate remarks and examples. Hinode requires the Markdown attribute `.blockquote` to properly render the block quote. See the following example from the [docs](https://gethinode.com/docs/content/typography/#blockquotes):

```markdown
> Tiam, ad mint andaepu dandae nostion secatur sequo quae.
> **Note** that you can use _Markdown syntax_ within a blockquote.
{.blockquote}
```

You could indeed add a shortcode to do the same, although I generally try to avoid adding shortcodes when a native markdown equivalent is available.

Having to add the attribute `.blockquote` is not ideal, but currently Hugo does not offer a [render hook](https://gohugo.io/render-hooks/) that we could tap into.

**Comment by Ipstenu** [comment]
> Having to add the attribute .blockquote is not ideal, but currently Hugo does not offer a [render hook](https://gohugo.io/render-hooks/) that we could tap into.

I was afraid of that (I'm still a relative GoLang newbie even after 5 years of Hugo). Thank you for the quick reply! Do you think it would be worth it to duplicate the `.blockquote` CSS for `blockquote {}` ? My gut was thinking "Well that would be a lot of work every time they update Bootstrap."

**Comment by markdumay** [comment]
I gave it some more thought - we could use the sass `@extend` rule to apply the `.blockquote` style to the `blockquote` element. There might be some drawbacks I'm unaware of, but the following examples seem to render as expected (copy it to a new content file such as `test.md`). I'll include the rule in an upcoming Hinode release.

```html
---
author: Mark Dumay
title: Blockquote test
---

## With attribute

### Simple

> Tiam, ad mint andaepu dandae nostion secatur sequo quae.
> **Note** that you can use _Markdown syntax_ within a blockquote.
{.blockquote}

### Reference

> Don't communicate by sharing memory, share memory by communicating.
>
> — _Rob Pike[^1]_
{.blockquote}

[^1]: The above quote is excerpted from Rob Pike's [talk](https://www.youtube.com/watch?v=PAAkCSZUG1c) during Gopherfest, November 18, 2015.

## Without attribute

### Simple

> Tiam, ad mint andaepu dandae nostion secatur sequo quae.
> **Note** that you can use _Markdown syntax_ within a blockquote.

### Reference

> Don't communicate by sharing memory, share memory by communicating.
>
> — _Rob Pike[^2]_

[^2]: The above quote is excerpted from Rob Pike's [talk](https://www.youtube.com/watch?v=PAAkCSZUG1c) during Gopherfest, November 18, 2015.
```

**Comment by markdumay** [comment]
@Ipstenu, we should have waited one more day... :-) 

Hugo [v0.132.0](https://github.com/gohugoio/hugo/releases/tag/v0.132.0) now supports [blockquote render hooks](https://gohugo.io/render-hooks/blockquotes/). I'll reopen this issue, so we can properly add the required Bootstrap attribute.

Hugo now also supports GitHub style alerts, which might be nice alternative for the [alert shortcode](https://gethinode.com/docs/components/alert/#alert-of-specific-type).

**Comment by Ipstenu** [comment]
I just saw that and laughed and laughed at my timing. Thank you for being so responsive! You're amazing.
