### ISSUE TITLE
[BUG] Search background flickers between light and back background when color primary color is used for navbar

### ISSUE THREAD

**Issue by TommyTran732** [gethinode/hinode#1083]
## Describe the bug

Search background flickers between light and back background when color primary color is used for navbar.

This is most visible if you disable dark theme.

## To reproduce

Set 

```
[navigation]
    color = 'primary'
    logo = 'img/logo.png'

[style]
    primary = '#7d2622'
```

Scroll up and down. See the background of the search box flickers.

## Expected behavior

Search box sticks to the appropriate light or dark theme.

## Screenshots

On my light themed website, it initially loads in with dark theme:

<img width="351" alt="Screenshot 2024-08-11 at 12 29 14" src="https://github.com/user-attachments/assets/40cb98df-0ae3-498c-a92c-a820cca7230a">

After I scroll down, it switches to light:

<img width="348" alt="Screenshot 2024-08-11 at 12 29 39" src="https://github.com/user-attachments/assets/eeddf8de-b017-4e18-b64e-e63bfa7251ad">

## Host environment

Please complete the following information where applicable.

 - Hinode version: v0.2.5
 - Hugo version: vv0.131.0
 - Browser: Microsoft Edge 127.0.2651.98

**Comment by TommyTran732** [comment]
I am running a dark system theme so that might be affecting it as well

**Comment by markdumay** [comment]
Does your navigation configuration include `overlay=true` by any chance? The [overlay setting](https://gethinode.com/docs/configuration/navigation/#basic-configuration) was added in Hinode v0.23.0.

**Comment by TommyTran732** [comment]
No, it is default, so it should be false

**Comment by markdumay** [comment]
I suspect it has something to do with the code that was added for the overlay support. However, I cannot reproduce your issue. Could you share the *exact steps* (or a repository) how to reproduce this? Do you use `npm`, `hugo`, `gethinode/hinode` or `gethinode/template`, etc. 

As a note, the provided information seems contradictory, for example, you specify `search = false` yet the screenshots do include a search box. 

> I am running a dark system theme so that might be affecting it as well

Is this set in the browser of somewhere else?

Lastly, does clearing the local cache (`Empty cache and Hard Reload` when using debugging tools in Chrome) do anything?

**Comment by TommyTran732** [comment]
> As a note, the provided information seems contradictory, for example, you specify search = false yet the screenshots do include a search box.

My bad, I disable it because of the flickering but forgot to remove it in there. I edited the original report to fix this.

> Is this set in the browser or somewhere else? I assume you use Windows given the use of Edge?

It is an OS setting. And I am using macOS.

> Lastly, does clearing the local cache (Empty cache and Hard Reload when using debugging tools in Chrome) do anything?

Nope, it does not.

**Comment by TommyTran732** [comment]
> However, I cannot reproduce your issue. Could you share the exact steps (or a repository) how to reproduce this? Do you use npm, hugo, gethinode/hinode or gethinode/template, etc.

I set it up in codespace.

Setting up the code space:

```
sudo apt update
sudo apt full-upgrade -y
sudo apt install golang -y
wget https://github.com/gohugoio/hugo/releases/download/v0.131.0/hugo_extended_0.131.0_linux-amd64.deb
sudo apt install ./hugo_extended_0.131.0_linux-amd64.deb
rm /usr/local/hugo/bin/hugo
ln -s /usr/local/hugo/bin/hugo /usr/local/bin/hugo
```

Set up hinode:

```
hugo new site my-hinode-site && cd my-hinode-site
hugo mod init example.com/my-hinode-site
echo "[[module.imports]]" >> hugo.toml
echo "path = 'github.com/gethinode/hinode'" >> hugo.toml
```

Configure param.toml:

```
[main]
    enableDarkMode = false
    endorse = false
    modes = 'light'

[navigation]
    color = 'primary'
    logo = 'img/logo.png'
#    search = false

[pages]
    [pages.default]
        metadata = 'original'

[sharing]
    enabled = false

[style]
    primary = '#7d2622'
 ```

Set your OS theme to dark theme.

Now, visit the site. See that the navbar initially loads in the dark theme, but if you scroll it correctly changes to white.

**Comment by TommyTran732** [comment]
Okay, so after I re-enabled the light-dark theme toggle, I also noticed the theme toggle looking weird after a reload: 

<img width="1302" alt="Screenshot 2024-08-12 at 08 06 14" src="https://github.com/user-attachments/assets/02602146-929f-4fb6-902c-f2210f78f48e">

To reproduce, use this param.toml:

```
[main]
    endorse = false

[navigation]
    color = 'primary'
#    logo = 'img/logo.png'
#    search = false

[pages]
    [pages.default]
        metadata = 'original'

[sharing]
    enabled = false

[style]
    primary = '#7d2622'
 ```

- Set the OS system theme to dark theme.
- Visit the site, toggle the theme to light theme.
- Open a new page. Observe how the search bar and light toggle looks like the screenshot.

**Comment by markdumay** [comment]
thanks - I'll look into it!

**Comment by markdumay** [comment]
Ok, I found the root cause of the issue. The navbar was setting the theme to dark when its color was set to either `primary`, `secondary`, `success`, `danger`, or `black`. However, the navbar's JavaScript reset this to 'null' whenever the function `updateNavbar()` was invoked.

I'll release a fix soon to remove the odd theme behavior. The navbar will no longer have a separate theme, unless in overlay mode. I'll also make sure the `updateNavbar()` will only update the navbar's theme when `data-bs-overlay` is initialized.
