### ISSUE TITLE
[BUG] Theme toggle button flickers

### ISSUE THREAD

**Issue by TommyTran732** [gethinode/hinode#1097]
## Describe the bug

Theme toggle flickers when loading a page.

## To reproduce

- Set up the same environment as https://github.com/gethinode/hinode/issues/1083
- Switch between pages
- Observe toggle flickers between light and dark extremely quickly
- The color for the icon of the toggle is also incorrect

## Expected behavior

The toggle does not flicker.

## Host environment

 - Hinode version: v0.25.5

**Comment by markdumay** [comment]
I've noticed the toggle button is inadvertently animated during page load (when the theme is set to light). I'll adjust the script, so the button is not animated visibly during page load. Is there any other side effect that I'm missing?

**Comment by markdumay** [comment]
I've fixed the colors and initial state of the toggle button. I shifted setting the initial state of the button from JavaScript to pure CSS, which should fully prevent any flickering / animations. I'll release the fixes soon. Feel free to test / share your feedback.

**Comment by TommyTran732** [comment]
That's all of the issues I have seen so far. I will lyk if I spot something else

**Comment by TommyTran732** [comment]
Okay, I updated to v0.25.7 and I no longer see any flicking issues 👍
