### ISSUE TITLE
Support Dart Sass transpiler

### ISSUE THREAD

**Issue by markdumay** [gethinode/hinode#119]
**Is your feature request related to a problem? Please describe.**
The build pipeline for Sass uses Hugo pipes to transpile the Sass files into CSS. Hugo uses LibSass by default, which is [deprecated](https://sass-lang.com/blog/libsass-is-deprecated) since October 2020. Dart Sass supports a flexible [module system](https://github.com/sass/sass/blob/main/accepted/module-system.md) among other features. No cross-platform solution of Dart Sass is available as of yet.

**Describe the solution you'd like**
Replace the LibSass library with Dart Sass. Ideally, the package is installed by npm automatically. The build pipeline should be able to ingest configuration values from Hugo, for example to set theme colors.

**Describe alternatives you've considered**
- [Bootstrap](https://github.com/twbs/bootstrap) uses Dart Sass to build its documentation site. However, it does not support Hugo configuration values. 
- Hugo provides a [workaround](https://discourse.gohugo.io/t/using-the-dart-sass-transpiler/41878) that uses Dart Sass embedded, which has the advantage to support Hugo variables natively. It is not fully compatible with npm yet.

**Additional context**
N/A

**Comment by markdumay** [comment]
There has been some progress regarding Hugo and dart sass since I created this issue. Biggest challenge that I see is that the runner (e.g. Netlify, GitHub actions) need to have the correct library installed too. I haven't found a solution that works with npm packages unfortunately.

My current focus is to finish the transition to native markdown, without having to rely on HTML content anywhere. It's almost done. I will then invest some time to reinvestigate this.

**Comment by Giom-fm** [comment]
Ok. Thanks for you work making this possible :)

What would be the argument against this [package](https://www.npmjs.com/package/sass)?
Except that it would probably be slower than the native implementation.

**Comment by markdumay** [comment]
I'm not sure it the current Hugo version is compatible with the package you mentioned. Last time I checked it was a pretty narrow validation by Hugo, where it literally scanned for the presence of a specific binary. But perhaps that has changed since.

**Comment by markdumay** [comment]
The command `hugo env` will tell you which libraries are detected/used by Hugo. Hinode uses an embedded (npm) version of Hugo for automation, which behaves a bit different than "plain" Hugo. The package is provided by the Bootstrap team, maybe they have discovered a way to make it work. It requires some investigation...

**Comment by Giom-fm** [comment]
I see.
Thanks for the clarification.

**Comment by markdumay** [comment]
I have created a fork to test the conversion to Dart-sass. I'll post my findings and observations in this thread.

**Comment by markdumay** [comment]
## Local environment

The Hugo docs describes how to [install Dart sass in a local development environment](https://gohugo.io/hugo-pipes/transpile-sass-to-css/#installing-in-a-development-environment). Run `hugo env` or `npm run env` to verify the platform.

**Comment by markdumay** [comment]
## GitHub runner

The GitHub runners do not have dart-sass preinstalled. We need to [install the required software in the workflow](https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners).

The following build step installs dart-sass for the main environments:

```yml
    - name: Install Dart Sass
      run:  |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo snap install dart-sass
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install sass/sass/sass
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install sass
        fi
      shell: bash
```

**Comment by markdumay** [comment]
## Production environments

The Hugo docs mention how to [install dart-sass for the following production environments](https://gohugo.io/hugo-pipes/transpile-sass-to-css/#installing-in-a-production-environment): GitHub Pages, GitLab Pages, and Netlify. Hinode currently uses Netlify for its deployment. The deployment options are being revised, but currently include [Azure blob storage](https://gethinode.com/docs/getting-started/hosting-and-deployment/).

### Netlify

Following the [Hugo docs](https://gohugo.io/hugo-pipes/transpile-sass-to-css/#netlify) we need to adjust the netlify.toml file with the following settings (**untested**):

```toml
[build.environment]
HUGO_VERSION = "0.115.1"
DART_SASS_VERSION = "1.63.6"
TZ = "America/Los_Angeles"

[build]
publish = "public"
command = """\
  curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  export PATH=/opt/build/repo/dart-sass:$PATH && \
  hugo --gc --minify \
  """
```

**Comment by markdumay** [comment]
## Stylesheet processing

We want to make the transpiler configurable in `params.toml`. We will introduce a new variable `main.build.transpiler`. The allowed values for the transpiler are `libsass` and `dartsass`, defaulting to `libsass`. 

```toml
[main]
    [main.build]
        transpiler = "dartsass"
```

The file `layouts/partials/head/stylesheet.html` defines the transpiler to be used. We will first read and validate the build configuration. Next, we will pass the setting to the CSS build pipeline.

```go-template
{{- $transpiler := site.Params.main.build.transpiler | default "libsass" -}}
{{- $supportedTranspilers := slice "libsass" "dartsass" -}}
{{- if not (in $supportedTranspilers $transpiler) -}}
    {{- errorf "partial [head/stylesheet.html] - Invalid value for param 'transpiler': %s" $transpiler -}}
{{- end -}}

{{- $options := (dict "transpiler" $transpiler "targetPath" $target "enableSourceMap" (not hugo.IsProduction) "vars" $vars) -}}
{{- $bundle := partial "utilities/bundle" (dict "match" $source "filename" (printf "scss/bundle-%d.scss" now.UnixNano) "modules" $modules "basepath" "scss" "debugging" site.Params.debugging.showSCSS) -}}

{{- $css := $bundle | resources.ExecuteAsTemplate $target . | toCSS $options -}}
```

**Comment by markdumay** [comment]
## Required modifications

### Hugo template variables

Hinode uses template variables to configure the stylesheet. The variables include the theme colors, theme font, navbar offset, and various dark mode helpers. The [initialization of these variables](https://discourse.gohugo.io/t/initialize-sass-variables-from-hugo-templates/42053) works a bit differently in Dart Sass.

**Libsass**

```scss
@import "hugo:vars";
```

**Dartsass**

```scss
@use "hugo:vars" as h;
```

We can then access these variables using the namespace `h`, e.g. `h.$primary;`. We will need to explicitly assign the Bootstrap variables. In libsass, this assignment is implicit.

### Conditional imports

The file `_syntax.scss` uses a workaround to import the syntax highlighting colors in dark mode.

```scss
@if $enable-dark-mode {
    [data-bs-theme="dark"] {
        @import "syntax-dark";
        [...]
    }
}
```

This workaround is not supported by dartsass. Instead, we can use the function `meta.load-css()` to include these syntax colors.

```scss
@use "sass:meta";

[...]

@if $enable-dark-mode {
    [data-bs-theme="dark"] {
        @include meta.load-css(syntax-dark);
        [...]
    }
}
```

### Deprecation warnings

Dartsass has deprecated a few functions that are being used by Hinode and/or Bootstrap.

- [Using / for division outside of calc() is deprecated](https://sass-lang.com/documentation/breaking-changes/slash-div/)
  This affects `assets/scss/common/_variables.scss`. The warning can be addressed by using `$primary-border-subtle-dark: mix(black, h.$primary, calc(h.$dark-mode-shade / 2)) !default;`
- [Passing percentage units to the global abs() function is deprecated](https://sass-lang.com/d/abs-percent)
  This affects `assets/scss/modules/bootstrap/_vendor/_rfs.scss`, part of `mod-bootstrap`. The warning can be addressed by replacing `abs()` with `math.abs()`. The `math` namespace needs to be included with `@use "sass:math";`.

**Comment by markdumay** [comment]
## Miscellaneous

Using the Dart Sass transpiler occasionally results in a timeout error:

> ERROR TOCSS-DART: failed to transform "css/main.css" (text/x-scss): "<stream>:1:1": timeout waiting for Dart Sass to respond; note that this project is only compatible with the Dart Sass Binary found here: https://github.com/sass/dart-sass/releases/

The timeout is not deterministic, which suggests a background process is not closed properly. Caching the core stylesheet appears to resolve the issue.

**Comment by markdumay** [comment]
@Giom-fm I've released an initial alpha version that supports Dart Sass. Your feedback is appreciated!

1. **Update go.mod**
  Update your `go.mod` file manually (by default, Hugo mod ignores prereleases)

    ```
    module github.com/owner/repository

    go 1.20

    require (
       github.com/gethinode/hinode v0.20.0-alpha
       [...]
    )
    ```

2. **Install the updated modules**
  `npm run mod:update`

3. **Update your build configuration**
  Add the following lines to your `params.toml`:

    ```toml
    [main.build]
        transpiler = "dartsass"
    ```

More information is available in the [docs](https://gethinode.com/docs/advanced-settings/styles/).

**Comment by Giom-fm** [comment]
Thanks for the sumup.
Unfortunately, it crashes with the following errors:

```ERROR render of "page" failed: execute of template failed: template: partials/head/head.html:6:7: executing "head" at <partialCached "head/stylesheet-core.html" .>: error calling partialCached: "/home/giom/repos/private/ff-eppendorf-website/_vendor/github.com/gethinode/hinode/layouts/partials/head/stylesheet-core.html:3:3": execute of template failed: template: partials/head/stylesheet-core.html:3:3: executing "partials/head/stylesheet-core.html" at <partial "head/stylesheet.html">: error calling partial: "/home/giom/repos/private/ff-eppendorf-website/_vendor/github.com/gethinode/hinode/layouts/partials/head/stylesheet.html:54:8": execute of template failed: template: partials/head/stylesheet.html:54:8: executing "partials/head/stylesheet.html" at <partial "head/icons.html" (dict "css" $css)>: error calling partial: "/home/giom/repos/private/ff-eppendorf-website/_vendor/github.com/gethinode/hinode/layouts/partials/head/icons.html:22:54": execute of template failed: template: partials/head/icons.html:22:54: executing "partials/head/icons.html" at <$css.Content>: error calling Content: TOCSS-DART: failed to transform "css/main.css" (text/x-scss): got unexpected EOF when executing "sass". The user running hugo must have read and execute permissions on this program. With execute permissions only, this error is thrown.
ERROR TOCSS-DART: failed to transform "css/main.css" (text/x-scss): got unexpected EOF when executing "sass". The user running hugo must have read and execute permissions on this program. With execute permissions only, this error is thrown.
ERROR TOCSS-DART: failed to transform "css/main.css" (text/x-scss): "<stream>:1:1": connection is shut down
Built in 609 ms
Error: error building site: TOCSS-DART: failed to transform "css/main.css" (text/x-scss): "<stream>:1:1": connection is shut down
```

Right now its unclear to me. Do I need to install dartsass or is it bundled in the hinode module?

**Comment by markdumay** [comment]
You will need to [install Dart Sass separately](https://gohugo.io/hugo-pipes/transpile-sass-to-css/#installing-in-a-development-environment). You can check your config with `hugo env`.

**Comment by markdumay** [comment]
Looking at the error message, it may be a permissions issue too? You may need to remove any previous installations of Dart Sass and reinstall using Hugo's guidelines.

**Comment by markdumay** [comment]
Meanwhile, I've released [v0.20.0-alpha2](https://github.com/gethinode/hinode/releases/tag/v0.20.0-alpha2). It uses a new [plugin for Netlify](https://github.com/gethinode/netlify-plugin-dartsass), if you're into that.

**Comment by Giom-fm** [comment]
Yeah I tried the npm solution which is leading to the error I posted.
Using the version you are also using in your Netlify plugin is working for me.

Thanks!

**Comment by markdumay** [comment]
OK, that's great! The codebase seems stable, I'll release the final version shortly. Let me know if you run into any issues.

**Comment by Giom-fm** [comment]
Ok running into the permission error again.
What is strange is that I encounter this error only if I use your npm scripts. Executing the hugo build command by hand is working fine.

```
./node_modules/.bin/hugo  env
hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended linux/amd64 BuildDate=2023-08-31T11:23:51Z VendorInfo=gohugoio
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.20.1"
github.com/sass/libsass="3.6.5"
github.com/webmproject/libwebp="v1.2.4"
github.com/sass/dart-sass/protocol="2.1.0"
github.com/sass/dart-sass/compiler="1.66.1"
github.com/sass/dart-sass/implementation="1.66.1"
```

Running `npm run build` leads to this error:
```
ERROR render of "page" failed: execute of template failed: template: partials/head/head.html:6:7: executing "head" at <partialCached "head/stylesheet-core.html" .>: error calling partialCached: "/home/giom/repos/private/ff-eppendorf-website/_vendor/github.com/gethinode/hinode/layouts/partials/head/stylesheet-core.html:3:3": execute of template failed: template: partials/head/stylesheet-core.html:3:3: executing "partials/head/stylesheet-core.html" at <partial "head/stylesheet.html">: error calling partial: "/home/giom/repos/private/ff-eppendorf-website/_vendor/github.com/gethinode/hinode/layouts/partials/head/stylesheet.html:54:8": execute of template failed: template: partials/head/stylesheet.html:54:8: executing "partials/head/stylesheet.html" at <partial "head/icons.html" (dict "css" $css)>: error calling partial: "/home/giom/repos/private/ff-eppendorf-website/_vendor/github.com/gethinode/hinode/layouts/partials/head/icons.html:22:54": execute of template failed: template: partials/head/icons.html:22:54: executing "partials/head/icons.html" at <$css.Content>: error calling Content: TOCSS-DART: failed to transform "css/main.css" (text/x-scss): got unexpected EOF when executing "sass". The user running hugo must have read and execute permissions on this program. With execute permissions only, this error is thrown.
ERROR TOCSS-DART: failed to transform "css/main.css" (text/x-scss): got unexpected EOF when executing "sass". The user running hugo must have read and execute permissions on this program. With execute permissions only, this error is thrown.
ERROR TOCSS-DART: failed to transform "css/main.css" (text/x-scss): "<stream>:1:1": connection is shut down
Total in 719 ms
Error: error building site: TOCSS-DART: failed to transform "css/main.css" (text/x-scss): "<stream>:1:1": connection is shut down
```

Running `./node_modules/.bin/hugo` is working fine.
Of course I have checked the permission and they look good to me. How do you execute your commands?
I will check if npm is spawning a subshell with another user but this seams odd.

**Comment by Giom-fm** [comment]
`sass --embedded is unavailable in pure JS mode.`

This seams strange. I dont have the JS version of dart-sass installed. Could you check if this is the same case in your setup?

**Comment by markdumay** [comment]
Yes, I added `npm run env` for that reason indeed. You can use it to verify if Hugo has found dart sass.

It's worth noting that dartsass is installed on your platform (host), whilst Hugo is embedded as npm binary. I haven't found a way yet to include dart sass as embedded npm binary yet.

**Comment by markdumay** [comment]
If Hugo can find dart sass, but still gives errors, I suspect you're running into a permissions error. I'm developing on macOS, so I cannot recreate your environment. However, the GitHub runner and Netlify runner both seem to work fine (both based on Ubuntu I believe).

**Comment by Giom-fm** [comment]
No its working now on my host and in the CI. It was really just the case that ` "sass": "^1.66.1"` was  added by mistake to package.json.
