### ISSUE TITLE
[BUG] simple-datatables.load.js 

### ISSUE THREAD

**Issue by d-oit** [gethinode/hinode#1221]
## Describe the bug

locale i18n labels not load of the simple-datatables.load.js 

## To reproduce
 
use table in lang  **de** or **nl** on a hinode page 

## Expected behavior

i18n transalation

If applicable, a clear and concise description of what you expected to happen.

## Log file

If applicable, add a copy of Hugo's log messages.

## Host environment

 "name": "@gethinode/mod-simple-datatables",
  "version": "1.0.13",

## Additional context

https://fiduswriter.github.io/simple-datatables/documentation/Options

the tableOptions could not load - already used sortable, etc variable.

**Comment by d-oit** [comment]
@markdumay https://github.com/d-oit/mod-simple-datatables working version used:
https://d-oit.github.io/de/blog/free-basketball-live-streams/

let tableOptions = { classes, tableRender, template not needed in my mind

**Comment by d-oit** [comment]
@markdumay 

fix is in:
https://github.com/d-oit/mod-simple-datatables

and 

https://github.com/d-oit/hinode/blob/main/layouts/shortcodes/table.html

in this way, the i18n localization text is used based on the site.lang

Did you find an other solution, or should i create a PR with this?

**Comment by d-oit** [comment]
@markdumay  https://github.com/gethinode/mod-simple-datatables/pull/56

with the changes, the table.html in hinode could extend with the new data-table-attributes

**Comment by markdumay** [comment]
thanks @d-oit! I've merged the two PRs.
