### ISSUE TITLE
[BUG] Documentation on https://gethinode.com/docs is missing commands mentioned in the text but is in the source code for that page

### ISSUE THREAD

**Issue by andrewrdavidson** [gethinode/hinode#1258]
## Describe the bug
Browsing the documentation on the https://gethinode.com/docs/getting-started/commands/ there is text:

<blockquote>
Starting a local server  
Use the following command from the command prompt to start a local development server. The command removes any previous build artifacts in the public and resources folders. The command invokes the local web server from Hugo, which watches for changes in the key system files and configuration directory. By default the generated site is available at http://localhost:1313/ and is responsive to changes. This allows for interactive development and testing. When in development mode, the generated assets (such as javascripts and CSS files) are not minified to simplify debugging.
</blockquote>
<blockquote>
Use the following command to mimic the site in production mode. In this setting, generated assets are minified and compliant with the Content Security Policy. Although Hugo’s web server is not meant to be run in a real production environment, it does allow validation of the site in an environment close to production
</blockquote>

But the commands are not shown.

Note: this may affect more than this one page, I have not checked the entire site. I noticed this whilst trying to follow the getting started guide

## To reproduce

1. Go to [https://gethinode.com/docs/getting-started/commands](https://gethinode.com/docs/getting-started/commands)
2. Go down to **Starting a local server** section.
3. The commands mentioned in the text of that section ("The command removes any previous build artifacts in the public and resources folders" and "Use the following command to mimic") are not displayed.
4. Go to the source of that page [https://github.com/gethinode/docs/blob/main/content/en/docs/latest/getting-started/commands.md](https://github.com/gethinode/docs/blob/main/content/en/docs/latest/getting-started/commands.md) and you will see that there are commands in there: `{{% command %}} npm run start {{% /command %}}` and `{{% command %}} npm run start:prod {{% /command %}}` respectively

## Expected behavior

The commands to appear as it makes following the documentation impossible

## Log file

n/a

## Screenshots

On the web page:

![image](https://github.com/user-attachments/assets/41ede980-99f2-4482-8293-7bc79f37d731)

In the code:

![image](https://github.com/user-attachments/assets/a58cf432-b46f-4702-bffb-8452c88825c9)

## Host environment

n/a as it's your own documentation site

## Hugo environment

n/a (see above)

**Comment by markdumay** [comment]
@andrewrdavidson, thanks for raising this issue. I've fixed it in this PR: https://github.com/gethinode/docs/pull/532. I didn't find any related issues, but feel free to reopen this issue if needed.

**Comment by andrewrdavidson** [comment]
No problem and thank you @markdumay for fixing so quickly! It makes a bit more sense now :-) I still have to get it to do what I want but that's not for here.
