### ISSUE TITLE
[BUG] params links build: https://demo.gethinode.com/ -> wrong link https://demo.gethinode.com/gethinode.com

### ISSUE THREAD

**Issue by d-oit** [gethinode/hinode#1266]
## Describe the bug

Copyright © 2024 Mark Dumay. | [Privacy](https://demo.gethinode.com/en/privacy/) | [Cookies](https://demo.gethinode.com/en/cookies/) | Powered by Hinode  ->> **https://demo.gethinode.com/gethinode.com**) .

## Screenshots

<img width="583" alt="image" src="https://github.com/user-attachments/assets/fb9f89d1-17c6-4661-8953-d07d4fa6cfbf">

**Comment by markdumay** [comment]
Thanks for spotting this. I fixed an error with cleaning the link's url: https://github.com/gethinode/hinode/pull/1269/files#diff-02697a4d5bc59d090e9862b2de6e38349ad55396d0f1625175974c0bcb7e5491

Feel free to reopen the issue if needed.
