### ISSUE TITLE
{{< file>}} add options for syntax highlight 

### ISSUE THREAD

**Issue by d-oit** [gethinode/hinode#1272]
## Problem or enhancement idea

add hugo highlight options to the file shortcode

## Proposed solution

{{< file full="true" show="false" path="./layouts/partials/navbar-mode.html" id="file-collapse-1" options="linenos=table,hl_lines=8 15-17,linenostart=3" >}}

use hugo syntax:
https://gohugo.io/content-management/syntax-highlighting/

## Solution: **file** shortcode
 
{{- $options := .Get "options" -}}
 {{- highlight (trim $content "\r\n") $lang $options -}}

**Comment by markdumay** [comment]
Thanks for submitting the PR @d-oit! I've merged the changes with the main branch. I'll move the content of the added post to the docs next.

**Comment by d-oit** [comment]
Thought in this way you could see directly the changes.

**Comment by markdumay** [comment]
It has been released: https://gethinode.com/docs/components/file/#syntax-highlighting
