### ISSUE TITLE
[BUG] sass -> breaking-changes/color-functions/ green, red, blue

### ISSUE THREAD

**Issue by d-oit** [gethinode/hinode#1277]
## Describe the bug

WARN  calling IsSet with unsupported type "ptr" (*hugolib.ShortcodeWithPage) will always return false.
WARN  Dart Sass: file://c/github/d-oit/hinode/_vendor/github.com/twbs/bootstrap/scss/_functions.scss:184:9: red() is deprecated. Suggestion:

color.channel($color, "red", $space: rgb)

More info: https://sass-lang.com/d/color-functions
WARN  Dart Sass: file://c/github/d-oit/hinode/_vendor/github.com/twbs/bootstrap/scss/_functions.scss:185:9: green() is deprecated. Suggestion:

color.channel($color, "green", $space: rgb)

More info: https://sass-lang.com/d/color-functions
WARN  Dart Sass: file://c/github/d-oit/hinode/_vendor/github.com/twbs/bootstrap/scss/_functions.scss:186:9: blue() is deprecated. Suggestion:

color.channel($color, "blue", $space: rgb)

More info: https://sass-lang.com/d/color-functions
WARN  Dart Sass: file://c/github/d-oit/hinode/_vendor/github.com/twbs/bootstrap/scss/_functions.scss:36:10: red() is deprecated. Suggestion:

color.channel($color, "red", $space: rgb)

More info: https://sass-lang.com/d/color-functions
WARN  Dart Sass: file://c/github/d-oit/hinode/_vendor/github.com/twbs/bootstrap/scss/_functions.scss:36:23: green() is deprecated. Suggestion:

color.channel($color, "green", $space: rgb)

More info: https://sass-lang.com/d/color-functions

## Host environment

Please complete the following information where applicable.

 - Hinode version: hinode@0.27.0-beta5

**Comment by markdumay** [comment]
Is this related to https://github.com/gethinode/hinode/issues/1060? The file`github.com/twbs/bootstrap/scss/_functions.scss` is an upstream file managed by the Bootstrap team, so it might be better to raise the issue there (if needed). Bootstrap v5.3.4 should fix #1060.
