### ISSUE TITLE
An issue with the menu navigation

### ISSUE THREAD

**Issue by prosodyteam** [gethinode/hinode#174]
**Describe the bug**
I renamed the files in 'content' folder and modified files in `config/_default`, but it still shows error: cols:0

**Reproduce the behavior**
1. Renaming files and filenames
2. change the title in the respective index
3. modify menu.toml
4. modify param.toml
5. hugo server/npm run start
6. "ERROR Invalid value for param 'cols': 0 Error: Error building site: logged 1 error(s)

**Expected behavior**
Rename folders and files in content without changing the original layout of theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/126227642/224676976-e7898fa4-54f0-4adc-838b-c50b125a8354.png)

**Environment (please complete the following information):**
 - Host  Windows 11
 - Node version: Node.js v18.15.0
 - Hugo version: hugo v0.111.2-4164f8fef9d71f50ef3962897e319ab6219a1dad+extended windows/amd64
 - Browser: Google Chrome Version 108.0.5359.124 (Official Build) (arm64)]

**Additional context**
Dear Mark,

I hope this message finds you well. First and foremost, I want to express my gratitude for creating such a beautiful and functional theme. It has been a pleasure working with it so far.
I am currently a student and I am helping my professor to build a website for our project showcase. I've run into an issue where I'm trying to update the navigation menu. I followed the steps of renaming folders and files, updating URLs, and modifying the menus file. However, every time I try to save and regenerate the site, I get an error message saying "Invalid value for param 'cols': 0".
I have followed the instructions in the documentation carefully, but I am still unable to resolve the issue. I would greatly appreciate any guidance or support you can offer to help me fix this problem.
Thank you in advance for your time and assistance.

Best regards,
Shaelyn

**Comment by markdumay** [comment]
Hi Shaelyn, thanks for your kind words - glad you like the theme! 

It's difficult to reproduce your error without any more information. In the future, it would be helpful if you could fill in the `Bug report` template when [submitting an issue](https://github.com/gethinode/hinode/issues/new/choose). Anyway, it seems an invalid value is passed to the [card group](https://github.com/gethinode/hinode/blob/main/layouts/partials/assets/card-group.html) partial. The `cols` parameter defines the number of columns for the grid (a group of cards) and should have a value between 1 and 5. The card group is an internal partial, which is being used by the [home page](https://gethinode.com/docs/0.9/configuration/layout/#home-page) and [list pages](https://gethinode.com/docs/0.9/configuration/layout/#list-pages).

The list sections are usually defined in `config/_default/params.toml`. Below is an excerpt of the main theme for the `Blog` section. The parameters `cols` is given as input to the card group and should have a value between 1 and 5.

```toml
[list]
    [blog]
        title = "Blog"
        sort = "date"
        reverse = false
        cols = 3
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom"
        homepage = 3
        separator = true
```

Hopefully this provides a hint on how to fix your issue. If you're still stuck, perhaps you could share your repository with me, so I can have a look in more detail.

I will update the documentation of the list page configuration in a future release, as right now it does not specify the valid input range.

**Comment by prosodyteam** [comment]
Dear Mark,

First of all, thank you for your reply and I would like to apologize for my previous non-standard bug report. I will make sure to improve my reports in the future.

I am a newcomer to Hugo (and programming in general), and have been struggling with the particular issue for some time now. Today, I spent the entire day trying to debug the issue and I have a question I would like to confirm with you.

I noticed that in the param.toml file, the [home] sections = ["blog", "projects"] section appears to be fixed code that cannot be changed. I am interested in renaming the blog and projects directories to something else, but as soon as I rename them, I receive the following error: "Error: Error building site: logged 1 error(s)".

I would greatly appreciate it if you could let me know if the code in the [home] sections is fixed or if there is a way for me to change it without causing an error.

Once again, thank you for your kind reply. I wanted to explain that the reason I did not include the repository was because I have not yet fully learned how to push local files to GitHub.

I look forward to your reply!

Best regards,
Shaelyn


________________________________
发件人: Mark Dumay ***@***.***>
发送时间: 2023年3月13日 13:06
收件人: gethinode/hinode ***@***.***>
抄送: prosodyteam ***@***.***>; Author ***@***.***>
主题: Re: [gethinode/hinode] An issue with the menu navigation (Issue #174)


Hi Shaelyn, thanks for your kind words - glad you like the theme!

It's difficult to reproduce your error without any more information. In the future, it would be helpful if you could fill in the Bug report template when submitting an issue<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgethinode%2Fhinode%2Fissues%2Fnew%2Fchoose&data=05%7C01%7C%7Ca09067dc67b34b22dfa208db2380bbe1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638142808044048108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=l31L4dKA19%2FRpQIXulePoirdera4svHJ88wTdobqGxo%3D&reserved=0>. Anyway, it seems an invalid value is passed to the card group<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgethinode%2Fhinode%2Fblob%2Fmain%2Flayouts%2Fpartials%2Fassets%2Fcard-group.html&data=05%7C01%7C%7Ca09067dc67b34b22dfa208db2380bbe1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638142808044048108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9TrrhrnwH3lvNVqqvDHKiaq21QMnrjl65%2BQ2ba92xbQ%3D&reserved=0> partial. The cols parameter defines the number of columns for the grid (a group of cards) and should have a value between 1 and 5. The card group is an internal partial, which is being used by the home page<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgethinode.com%2Fdocs%2F0.9%2Fconfiguration%2Flayout%2F%23home-page&data=05%7C01%7C%7Ca09067dc67b34b22dfa208db2380bbe1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638142808044048108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5Tok3TplzDrD7if6f745LFBdDGaDz83QOSe49ArIpPY%3D&reserved=0> and list pages<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgethinode.com%2Fdocs%2F0.9%2Fconfiguration%2Flayout%2F%23list-pages&data=05%7C01%7C%7Ca09067dc67b34b22dfa208db2380bbe1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638142808044048108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iXQpKAil%2BLyPziw8%2FQNWPzx6F1unNnCZW%2Fhwve5dx%2FA%3D&reserved=0>.

The list sections are usually defined in config/_default/params.toml. Below is an excerpt of the main theme for the Blog section. The parameters cols is given as input to the card group and should have a value between 1 and 5.

[list]
    [blog]
        title = "Blog"
        sort = "date"
        reverse = false
        cols = 3
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom"
        homepage = 3
        separator = true

Hopefully this provides a hint on how to fix your issue. If you're still stuck, perhaps you could share your repository with me, so I can have a look in more detail.

I will update the documentation of the list page configuration in a future release, as right now it does not specify the valid input range.

―

**Comment by markdumay** [comment]
No worries! Hugo can be quite overwhelming in the beginning. The `sections` refer to the name of a so-called Hugo section. You might want to familiarize yourself with Hugo's documentation about [content sections](https://gohugo.io/content-management/sections/).

The sections are by no means fixed, however, they should point to a valid content section. Take a look at the [docs repository](https://github.com/gethinode/docs) for example. Is displays a single section called `features`, which is defined in `content/en/features`. It includes an `_index.md` file to make it a page bundle (e.g. list page). The section is then defined in `config/_default/params.toml`:

```toml
[home]
    sections = ["features"]

[...]

[list]
    [features]
        title = ""
        [...]
```

More information is available in Hinode's [content organization](https://gethinode.com/docs/0.9/content/content-organization/). Hope this helps!

PS: you might want to use the [Hinode child repository](https://github.com/gethinode/child) as starting point for your own project. Simply click on the green button `Use this template` at the top of the screen. You can then initialize your own repository, either private or public. Once set up, simply use the following command to synchronize the remote Git repository with your local computer: `git clone git clone https://github.com/<yourname>/<yourrepo>.git`. See the [Introduction ](https://gethinode.com/docs/0.9/getting-started/introduction/)for more details. Using [VSCode ](https://code.visualstudio.com/)for example, you can modify your files locally and push them to GitHub when done. You might want to set up a development branch first.

**Comment by prosodyteam** [comment]
Thank you Mark. So nice of you!
I will listen to your suggestions and I hope I can make progress soon!

Also, this is my project's repository (I appreciate your guidance): https://github.com/prosodyteam/prosodyteam.github.io
I modified sections by email, but it still shows cols error. And maybe now I can finally see where the problem lies.

Thanks again!

Best,
Shaelyn
________________________________
发件人: Mark Dumay ***@***.***>
发送时间: 2023年3月13日 17:22
收件人: gethinode/hinode ***@***.***>
抄送: prosodyteam ***@***.***>; Author ***@***.***>
主题: Re: [gethinode/hinode] An issue with the menu navigation (Issue #174)


No worries! Hugo can be quite overwhelming in the beginning. The sections refer to the name of a so-called Hugo section. You might want to familiarize yourself with Hugo's documentation about content sections<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgohugo.io%2Fcontent-management%2Fsections%2F&data=05%7C01%7C%7Ce72d1f0565c24690283808db23a47a45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638142961561664296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=j3a1vtVgHufiSqbHZrCiQvfpaTqezxsTgtk2nBkApdw%3D&reserved=0>.

The sections are by no means fixed, however, they should point to a valid content section. Take a look at the docs repository<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgethinode%2Fdocs&data=05%7C01%7C%7Ce72d1f0565c24690283808db23a47a45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638142961561664296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=M82eKporbcjoHQkyxahojDhqz4ng7U%2BG7IbTdtcy9Pg%3D&reserved=0> for example. Is displays a single section called features, which is defined in content/en/features. It includes an _index.md file to make it a page bundle (e.g. list page). The section is then defined in config/_default/params.toml:

[home]
    sections = ["features"]

[...]

[list]
    [features]
        title = ""
        [...]

More information is available in Hinode's content organization<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgethinode.com%2Fdocs%2F0.9%2Fcontent%2Fcontent-organization%2F&data=05%7C01%7C%7Ce72d1f0565c24690283808db23a47a45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638142961561664296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=41PX2fz%2FZcLCAVTrNcRX5WCrzzgSLu89Kr4Ts3tkm7c%3D&reserved=0>. Hope this helps!

PS: you might want to use the Hinode child repository<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgethinode%2Fchild&data=05%7C01%7C%7Ce72d1f0565c24690283808db23a47a45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638142961561664296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZVx1m%2BiQhquR9dF7EgGLzKpVGYfmr4k05ZCMuTdPqG8%3D&reserved=0> as starting point for your own project. Simply click on the green button Use this template at the top of the screen. You can then initialize your own repository, either private or public. Once set up, simply use the following command to synchronize the remote Git repository with your local computer: git clone git clone https://github.com/<yourname>/<yourrepo>.git. See the Introduction <https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgethinode.com%2Fdocs%2F0.9%2Fgetting-started%2Fintroduction%2F&data=05%7C01%7C%7Ce72d1f0565c24690283808db23a47a45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638142961561664296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=m1siKsl0IWT%2F2peLrnexVnk4UzAYbRquto3XxwP7sYM%3D&reserved=0> for more details. Using VSCode <https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcode.visualstudio.com%2F&data=05%7C01%7C%7Ce72d1f0565c24690283808db23a47a45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638142961561664296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xBd4geE%2Bk%2BvhyRb%2BjU5NMuqSpVl6EtKOoC2SczeaRZg%3D&reserved=0> for example, you can modify your files locally and push them to GitHub when done. You might want to set up a development branch first.

―

**Comment by markdumay** [comment]
Thanks for sharing your repo. It seems the content sections for `en` and `nl` are out-of-sync. Renaming the folders in `nl` should do the trick.

You can further simplify your setup if you do not plan to create a multi-language site. Some additional changes then are:
- Delete the `content/nl` folder entirely
- Set `defaultContentLanguageInSubdir` to `false` in `config.toml`
- Update the `link` value `en/about` to `/about` in `[en.params.feature]`
- Remove `[nl]` and all its child entries entirely from `languages.toml`

**Comment by prosodyteam** [comment]
>It seems the content sections for en and nl are out-of-sync. Renaming the folders in nl should do the trick.

Yes! It is indeed `en` and `nl` are out-of-sync that causes the error. Because we wanted to make a bilingual (English and Chinese) website, I deleted `nl` and wrote my own `zh.yaml` and changed the relevant `toml` files. Now, it works :D

Thank you Mark!

**Comment by markdumay** [comment]
Great to hear it works now. Good luck with setting up your site!
