### ISSUE TITLE
Manual Install Option

### ISSUE THREAD

**Issue by Dekker500** [gethinode/hinode#211]
I am kicking the tires on Hinode... but have been left scratching my head...

For those of us who choose not to use full automation for deployment, could you consider a fallback in your docs on how to `build` and `build:prod` to the local `/public` folder?

This would make it much easier for those of us on other platforms to grab the results and host them elsewhere, like AWS, or internal corporate servers.

Much appreciated!

**Comment by Dekker500** [comment]
Oops. Duplicate of https://github.com/gethinode/hinode/issues/121

Closing this one...

**Comment by markdumay** [comment]
Glad you like the theme! I'll add a manual deployment section.

Meanwhile, is the following command helpful?
https://gethinode.com/docs/0.9/getting-started/commands/#generating-a-web-site
