### ISSUE TITLE
[BUG] - Icon Short code in H1, H2, taints the side  menu

### ISSUE THREAD

**Issue by creslinux** [gethinode/hinode#222]
**Describe the bug**
Using a short code, explicitly tested a Font Awesome Icon, in a markup header spoils the side menu with "HAHAHAHUGOSHORTCODE" strings 

By way of example the markdown
`## Maori Tattoos - Fact Box {{< fas vault >}}`

produces an entry in the side menu that reads as:
`[Maori Tattoos - Fact Box HAHAHUGOSHORTCODEs0HBHB]`
And links to 
`(http://localhost:1313/en/posts/maori-tattoos/#maori-tattoos---fact-box-hahahugoshortcodes0hbhb)`

**To reproduce**
1. Go to 'any blog post, update a header to include a shortcode icon`
2. Click on 'load the post in a browser
3. See error

**Expected behavior**
Either the Icon to be ignored in the side menu - the Text part only to show

**Screenshots**
![Screenshot from 2023-04-24 18-46-27](https://user-images.githubusercontent.com/34645187/234009423-b2148417-5e02-415d-8159-e1ecdecefa37.png)

![Screenshot from 2023-04-24 18-46-46](https://user-images.githubusercontent.com/34645187/234009388-27175fd8-3c6f-41b7-98f8-dfcb94adba7c.png)

**Environment (please complete the following information):**
 - Hinode version: main - pulled Apr 24 2023
 - Host OS: Ubuntu 20.04 with T2 kernel on MBP 2019
 - Node version:  8.18.0
 - Hugo version: hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended linux/amd64 BuildDate=2023-03-12T11:40:50Z
 - Browser: Brave (Official Build) (amd64)]

**Comment by markdumay** [comment]
Personally I'm not convinced you  should be mixing the heading with metadata, see this [thread](https://discourse.gohugo.io/t/how-to-add-fontawesome-icon-to-title-in-front-matter/31775/1) as well. 

I haven't tested the following suggestions yet, but these might be of help:
- You could consider using emoji instead of icons
- You could try a [pulled FA icon](https://gethinode.com/docs/0.9/content/icons/#bordered-and-pulled-icons)

**Comment by creslinux** [comment]
Ahh - ok. Its a shame thought they looked well in the headings. 
Thanks for the tip - I'll move the icons to other places in the page

Shall I close this?

**Comment by markdumay** [comment]
I gave it some more thought; an additional approach could be to use [attributes](https://gohugo.io/getting-started/configuration-markup/#goldmark) with a [custom render hook](https://gohugo.io/templates/render-hooks/#context-passed-to-render-heading).

You would add the Font Awesome attributes to the heading. The single curly brackets should be put directly below the heading:

```markdown
## Maori tattoos - Fact Box
{.fa-solid .fa-vault}
```

Then you would customize the render hook defined in `layouts/_default/_markup/render-heading.html`. This example adds the icon to the right of the heading:

```html
{{- $attributes := "" -}}
{{- with (index .Attributes "class") }}{{ $attributes = printf "<i class=\"%s\"></i>" . }}{{ end -}}

{{ if site.Params.navigation.anchor }}
<h{{ .Level }} id="{{ .Anchor | safeURL }}" class="heading">{{ .Text | safeHTML }} {{ $attributes | safeHTML }} <a href="#{{ .Anchor | safeURL }}"><i class="fa-solid fa-link anchor"></i></a></h{{ .Level }}>
{{ else }}
<h{{ .Level }} id="{{ .Anchor | safeURL }}">{{ .Text | safeHTML }} {{ $attributes | safeHTML }}</h{{ .Level }}>
{{ end -}}
```
