### ISSUE TITLE
defaultContentLanguageInSubdir and links in languages.toml

### ISSUE THREAD

**Issue by strauhmanis** [gethinode/hinode#246]
**Is your feature request related to a problem? Please describe**
The problem is that the functioning of the option _defaultContentLanguageInSubdir_ depends on the hardcoded into _languages.toml_ links (i.e. "/en/about").

**Describe the solution you'd like**
Although, I do not know whether there is   or   is no limitation with the Hugo to arrive at this specific solution, my description of it is as follows:

Perhaps, and in the example of the "/en/about" link, it could be possible for the "en" part to be generated dynamically depending on the high-level definition in the languages.toml (i.e. "[en]" and "[nl]" and "[mylang]"), and depending on whether the _defaultContentLanguageInSubdir_ option is true or false, as well as depending on the weight.

**Describe alternatives you've considered**
As is now, the alternative to the proposed solution, is to change the hardcoded links by hand whenever the _defaultContentLanguageInSubdir_ is set to true or false and whenever language's weight is altered.

**Additional context**
Please see the attached screenshot in respect to the proposed solution.

![Screenshot](https://github.com/gethinode/hinode/assets/17160191/fa34f260-a77e-4cb5-9393-89082406796d)

**Comment by markdumay** [comment]
Thanks for pointing this out, I agree the current configuration is kind of messy. I submitted a new release to fix this, see this [PR](https://github.com/gethinode/hinode/pull/248) for the changes. All URLs should now be decoupled from the language configuration. Let me know if this behaves as expected.

Regarding the `contentDir`, this depends on your specific Hugo configuration. You can [organize content translations](https://gohugo.io/content-management/multilingual/#translate-your-content) by either content directory or by filename. Hinode uses organization by content directory as an example, but you should be able to adjust this in your own project as desired.

**Comment by strauhmanis** [comment]
Thank you very much, Mark!
The change you introduced is excellent and behaves as excepted!
