### ISSUE TITLE
Add version switch support for documents

### ISSUE THREAD

**Issue by hustcer** [gethinode/hinode#247]
Thanks for creating this theme. It is the best hugo theme I have ever seen.

**Is your feature request related to a problem? Please describe.**

For a typical project, they may have docs for different versions, It would be great to switch between the versions

**Describe the solution you'd like**

Just like the lodash docs here: https://lodash.com/docs/3.10.1, they have a version switcher for that

**Describe alternatives you've considered**

List all available versions works too, just like this one: https://ziglang.org/documentation/0.10.1/

Maybe we can support both?

**Additional context**

Thanks again.

**Comment by markdumay** [comment]
Glad you like the theme! I'll add your request to the wishlist.

**Comment by markdumay** [comment]
Another strategy that comes to mind is to download the content of a specific release to a temp directory. You can then use `hugo mount` to add the relevant content to the virtual file system.

Some considerations:
- Avoid duplicating content files (e.g. make use of the repository's tagged releases)
- Avoid hosting-specific deployments (e.g. Netlify branch deployments only work on their platform obviously)
- Ideally the solution is compatible with Linux, macOS, and Windows (although most runners are Linux based, this is not - catering for local development)
- The menu data (`data/docs.yml`) should be mounted too, and should be version aware
- The approach should work work both locally and as part of a CI/CD workflow

**Comment by hustcer** [comment]
Great, I will give it a try. Thanks

**Comment by markdumay** [comment]
I did some testing, and noticed the mounting approach introduces some side effects:
- Page links (`relref`or `ref`) might become ambiguous
- Paga aliases might introduce conflicts

Possibly this could be tackled with a shell script. The script would replace all page links with a version-aware shortcode (e.g. `docsref` and strip all aliases from the mounted files. The mounted files would have to be added to `.gitignore`.

**Comment by markdumay** [comment]
I did some additional experimentation and concluded the mounting approach has too many unwanted side effects. Instead, I intent to support both other two approaches:
1. **Basic** - Create subfolders within the same repository (e.g. `docs/0.9`, `docs/1.0`)
2. **Advanced** - Support multi-branch deployments (use Git tags to deploy a versioned branch and redirect them on the server)

The idea is to use the site parameters to define the various versions, and to automatically include them in the navbar. I'm working on a test repository at the moment. I'll also prepare a new guide that illustrates the approach. I'll keep you posted.

**Comment by hustcer** [comment]
Wow, That's great, thanks for always improving this. 👏  👍

**Comment by markdumay** [comment]
I'm working on the advanced approach right now. The [redirection for Netlify requires some special configuration](https://honnef.co/articles/generating-netlify-_redirects-from-hugo/).

**Comment by markdumay** [comment]
I released `0.15.0-beta3` to support multi-branch deployments. The [demo repository](https://github.com/gethinode/version-demo) and [live demo](https://version-demo.gethinode.com/) have been updated too.

Next to some rigorous testing, I plan to work on the following items:
- Add a dismissible alert to the top of the page when a newer version of the docs is available
- Update the documentation on https://gethinode.com
- Write a guide on how to enable / configure versioned documentation (basic and advanced)

**Comment by markdumay** [comment]
Release `0.15.0-beta5` now introduces support for dismissible alerts. The code checks if the current version is the latest and adds an alert to the top of the page if applicable. The alert is version-aware (meaning it checks each individual version page) and can be dismissed per session - open a new tab to clear the session data.

**Comment by hustcer** [comment]
Great work! Then we can close this issue any time.

**Comment by markdumay** [comment]
Thanks! Does it work as expected? 

I'll first finish the docs and guide before closing the issue. I'll release the final `v0.15.0` next (if any known issues have been addressed).

**Comment by hustcer** [comment]
I'm quite busy recently and will try it later， Thanks again

**Comment by markdumay** [comment]
I have released the final `v0.15.0`. You can find a guide on https://gethinode.com/guides/versioning/. The guide includes a link to a demo repository.

I'll close the issue for now, feel free to share your feedback anytime.
