### ISSUE TITLE
[BUG] fontawesome brand icons not working

### ISSUE THREAD

**Issue by phkim14** [gethinode/hinode#282]
**Describe the bug**
The fontawesome brand icons are not working properly. 

**To reproduce**
1. Go to https://gethinode.com/docs/0.9/getting-started/introduction/
2. You can see that any of the brand icons are just square, not actual icons. For example, the menu on the top right corner to change the color scheme, you don't see the icons for "light", "dark", and "auto".  

**Expected behavior**
The squares should actually be icons.

**Screenshots*
<img width="1084" alt="Screenshot 2023-06-04 at 13 23 36" src="https://github.com/gethinode/hinode/assets/32853750/f3415e70-2dc0-4103-951e-c8780bd2d68b">

**Environment (please complete the following information):**
 - Hinode version: v0.14.6
 - Host OS: macOS Ventura 13.4
 - Node version: Node.js v20.2.0
 - Hugo version: hugo v0.112.7+extended darwin/arm64 BuildDate=unknown
 - Browser: Google Chrome Version 114.0.5735.90

**Comment by markdumay** [comment]
Thanks for spotting this! It should be fixed now (as well as for the template repo).
