### ISSUE TITLE
Go Module Support

### ISSUE THREAD

**Issue by doganulus** [gethinode/hinode#314]
I wonder if Go modules can be an option for getting Hinode? 

I usually want to avoid the whole Javascript ecosystem as much as possible.

**Comment by markdumay** [comment]
It’s quite a fundamental design choice for Hinode to utilise the npm ecosystem. You could use CDN for the various libraries (such as bootstrap and fontawesomej, but you’d lose the ability of automated dependency upgrades. It’s not an approach I plan to support unfortunately.

**Comment by markdumay** [comment]
I might have some good news for you. I'm working on support for Hugo modules. The npm packages are being shifted to modules instead, meaning that you are no longer required to use npm when using the theme. Instead, the use of npm becomes optional (unless you want to develop / customize the modules themselves).

An [initial alpha release](https://github.com/gethinode/hinode/releases/tag/0.16.0-alpha) is available on GitHub. It still being developed and no documentation is available yet.

**Comment by markdumay** [comment]
Released with v0.16.0
