### ISSUE TITLE
[BUG] Breadcrumbs are not visible

### ISSUE THREAD

**Issue by myrthos** [gethinode/hinode#317]
When `breadcumbs` is enabled in `params.toml`, they are not visible as they are overlapped by something else. What is just visible is the very bottom part of some of the characters in the breadcrumb.

**To reproduce**
1. Set breadcrumbs to true in `params.toml`. 
2. Once the site rebuilds, some very small parts of the breadcrumbs are visible, below the search box.

**Expected behavior**
Obviously I expected the breadcrumbs to show :)

**Screenshot**
![breadcrumb](https://github.com/gethinode/hinode/assets/19652599/4bfdb6c0-9834-4372-a2ae-66ecf889cf7b)
The screenshot shows, what is displayed when breadcrumbs are enabled and the 'Bootstrap elements' page is displayed. But, it is the same on every page that is supposed to show breadcrumbs. What is shown are some very small fragments of the characters in the breadcrumb like the very low part of the letter 'g' in 'Blog'.

**Environment**
 - Hinode version: v0.15.1, but actually using template v0.8.2 (the issue is there on both)
 - Host OS: Linux Mint Vera (21.1)
 - Node version: v18.16.1
 - Hugo version: hugo v0.114.0-9df2ec7988e5a217a14901cc76c0b7e76b2e9f02+extended linux/amd64 BuildDate=2023-06-19T17:01:43Z VendorInfo=gohugoio
 - Browser: Tested on Firefox 114.0.2 and on Brave version 1.52.129 (using Chromium 114.0.5735.198)

**Additional context**
I can fix the problem by editing the file: `node_modules/bootstrap/scss/_variables.css` and change the line `$breadcrumb-padding-y:` to `1rem !default`. This is the first time I work with nodejs, so I suppose there probably is a neater way of fixing this besides editing bootstrap files, but I am unclear on where I should fix that.
Also this fix makes the breadcrumbs visible, but also increases the space between the breadcrumbs and the title, which looks to be a bit much.
I am using the Hinode template myself, but I checked if it is also in this repository by cloning it and enabling the breadcrumbs and it indeed shows the same issue.

**Comment by markdumay** [comment]
Thanks for reporting this, I can confirm it is a bug. The breadcrumb is hidden when using a fixed navbar. I'll submit a fix.

**Comment by myrthos** [comment]
Thanks for the quick fix. At first I thought the result was the same as before, but I forgot that I increased the logo size to 50 in navbar.html, so for me the multiplacation factor needs to be 0.5. So, it works now.

I do want to add that it is a very good theme. I checked a couple of other themes as well, but this one ticked all the (major) boxes. Even though I did have to make a few changes to the theme, to have it also tick some of the minor boxes, it is still a great theme. Thanks for making and sharing it.

**Comment by markdumay** [comment]
Glad it works now. The multiplication factor was indeed intended to be customizable. The documentation is available on https://gethinode.com/docs/components/breadcrumb/#customization, but you already figured that out yourself.

Thanks for your kind words! Glad you like the theme. Feel free to share your suggestions for further improvement!
