### ISSUE TITLE
Add a class as a parameter to the search-input partial

### ISSUE THREAD

**Issue by myrthos** [gethinode/hinode#382]
**Is your feature request related to a problem? Please describe.**
I prefer the search box to stand out a bit more than it does. Before it was a module I changed one of the classes to get a thin border. Now that it is a module that is no longer possible.

**Describe the solution you'd like**
Instead of adding another hack for this, it would be good if the `search-input` partial gets a "class" parameter, which will add that class to the `input` tag (after the current classes).

**Describe alternatives you've considered**
The simplest alternative is to copy the current class used in the partial, put it in a a .scss file and change the border in the class to 1. Then make sure that this new file with the changed class definition, is loaded after the class definition of the module, which has the same name.  
Although this is not a too bad solution, I also think it is confusing to have multiple class definitions with the same name. Besides, having it as a parameter, offers more opportunities for those who want to style the search box differently.
I'm aware that I need to modify the `navbar` partial for adding the class when the `search-input` partial is called, but I already need to change the `navbar` partial, as I  have the search box on the right side.

**Comment by markdumay** [comment]
I standardized the various shortcodes and added support for an optional `class` argument where it made sense. I did the same for the `mod-flexsearch` component. The refinements are included in [release v0.17.4](https://github.com/gethinode/hinode/releases/tag/v0.17.4).

**Comment by myrthos** [comment]
I have not tried the other changes (yet), but the change to mod-flexsearch works great. Thanks a lot :+1:
