### ISSUE TITLE
Make comments aware of the current style

### ISSUE THREAD

**Issue by myrthos** [gethinode/hinode#383]
**Is your feature request related to a problem? Please describe.**
The Utterances javascript code in the `comments` partial, is not aware of the currently selected color (dark or light). When the user selects a different color than the default or the color set as a parameter, the styling of the comments is off.

**Describe the solution you'd like**
When no theme for the comments is specified in `params.toml`, follow the theme of the site.

**Describe alternatives you've considered**
I have enabled automatic theme switching in the `comments` partial in the following way:

```go-html-template
{{- $params := .Site.Params.comments -}}
{{- with $params -}}
<h2>{{ T "comments" }}</h2>
<div class="d-none-light">
  <script src="https://utteranc.es/client.js"
    repo="{{ $params.repo }}"
    issue-term="{{ default "pathname" $params.issueTerm }}"
    label="{{ default "comment" $params.label }}"
    theme="{{ default "github-dark" $params.theme }}"
    crossorigin="anonymous"
    async>
  </script>
</div>
<div class="d-none-dark">
  <script src="https://utteranc.es/client.js"
    repo="{{ $params.repo }}"
    issue-term="{{ default "pathname" $params.issueTerm }}"
    label="{{ default "comment" $params.label }}"
    theme="{{ default "github-light" $params.theme }}"
    crossorigin="anonymous"
    async>
  </script>
</div>
{{- end -}}
```
It is the only way I am aware of on how to solve this issue. I don't know if there is another way, but I only list it here as an example.  
Regardless of whether or not it is a good solution, as comments are supported by the Hinode template, I do think that Hinode should support theme switching for comments as well, which is why I am suggesting this feature request.

Edit: probably a better solution is to have the JavaScript code in a separate partial with the default theme as a parameter. In that case there is no duplication of code.

**Comment by markdumay** [comment]
Thanks! I'll include it in a new module for utterances. This is very early code and doesn't bundle the scripts for example.

**Comment by markdumay** [comment]
See #695
