### ISSUE TITLE
[BUG] hinode v0.17.3 fails to build site due to missing docs shortcode

### ISSUE THREAD

**Issue by Metisweb** [gethinode/hinode#389]
In order to install the Hinode Template I followed the instructions on page:
https://gethinode.com/docs/getting-started/introduction/

When starting the Hugo server (command: hugo server) an error was encountered. See below.

Error: Error building site: "/Users/dev/Websites/my-hinode-site/content/en/blog/bootstrap-elements.md:171:1": failed to render shortcode "docs": failed to process shortcode: "/var/folders/kq/n5mz5ryd7sd7vqgytfyw5psm0000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/github.com/gethinode/hinode@v0.17.3/layouts/shortcodes/docs.html:61:17": execute of template failed: template: shortcodes/docs.html:61:17: executing "shortcodes/docs.html" at <os.Stat>: error calling Stat: file does not exist

Workaround - Removing the docs shortcode call in files:
content/blog/en/bootstrap-elements.md
content/blog/nl/bootstrap-elements.md

**Comment by markdumay** [comment]
I suspect the basePath is out-of-sync. Does the following adjustment in `config/_default/params.toml` fix it?

```toml
[docs]
    basePath = "_vendor/github.com/gethinode/hinode"
```

Anyways, I updated the template repository and made some additional adjustments.

**Comment by markdumay** [comment]
One more remark, it looks like your modules are not vendored given the path `/var/folders/kq/n5mz5ryd7sd7vqgytfyw5psm0000gn/T/[...]`. Vendoring is a prerequisite for the modules to work properly. You might want to check if your `package.json` is up-to-date? I made some additional refinements in the latest release.

Meanwhile, I'm working on improving the initial setup of Hinode. My aim is to support both a "regular module setup" (using Hugo only) and an "advanced setup" (using npm). I'll update the instructions accordingly (both the readme and [docs](https://gethinode.com/docs/getting-started/introduction/)).
