### ISSUE TITLE
Add support for French Language

### ISSUE THREAD

**Issue by aefly** [gethinode/hinode#399]
Hi,

I'm interested in adding French language support, this could improve accessibility!

**Comment by markdumay** [comment]
Thanks for your offer @aefly, that would be a nice addition indeed! Would you be willing to maintain these translations too?

I suggest we clean up the current i18n files first - right now they contain some legacy stuff that is no longer needed. Once we have all the proper i18n definitions, we could showcase the French support on the demo site (https://demo.gethinode.com) too. 

Right now, the demo site contains two pages to test [Bootstrap functionality](https://demo.gethinode.com/en/blog/bootstrap-elements/) and to validate [module support](https://demo.gethinode.com/en/blog/components/). I'm considering not to translate these two pages, as it requires quite some maintenance and they are frequently modified. We could simply omit them from all translations, except the English version.

What are your thoughts?

**Comment by aefly** [comment]
Thank you for your detailed explanations!

Both PR are waiting for review: [hinode](https://github.com/gethinode/hinode/pull/405) - [mod-flexsearch](https://github.com/gethinode/mod-flexsearch/pull/14)

**Comment by markdumay** [comment]
Thanks! I've merged both PRs. I'm working on improving overall accessibility and have introduced two new i18n items. Would you care to provide a translation for them as well?

```yaml
- id: shareSystem
  translation: "system" # placeholder
- id: copyToClipboard
  translation: "copy to clipboard" # placeholder
```

**Comment by aefly** [comment]
Of course, I've [updated](https://github.com/gethinode/hinode/pull/411) these two items

**Comment by markdumay** [comment]
Thanks again for your support! The files have been merged into the main branch. I will release v0.18 including the FR support soon.
