### ISSUE TITLE
[BUG] npm ci fails

### ISSUE THREAD

**Issue by myrthos** [gethinode/hinode#458]
**Describe the bug**
`npm ci` no longer runs and returns with an `EBADPLATFORM` error .

The reason for this is that `"fsevents": "~2.3.2"` is Mac only?

It happens on this line: `"node_modules/markdownlint-cli2/node_modules/fsevents"`  
Adding `"optional": true, ` fixes the problem

**To reproduce**
Run npm ci on anything else than a Mac

**Expected behavior**
I expected it to work, as before.

**Log file**
These are the messages when running `npm ci`:

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin"} (current: {"os":"linux"})
npm ERR! notsup Valid os:  darwin
npm ERR! notsup Actual os: linux
```

**Additional context**
I don't have a mac :grinning:

**Comment by markdumay** [comment]
That's strange... I run `npm ci` for macOS, Windows, and Ubuntu upon each merge request - see [lint-build.yml](https://github.com/gethinode/hinode/blob/main/.github/workflows/lint-build.yml). I'll try this on a local Windows machine.

**Comment by myrthos** [comment]
I get it after I merge the latest Hinode codebase with mine. I need to add that line to get it to work.  
Did that again yesterday and had the same error. If it works for you then something happens when I merge.

I will try to find out what is happening.

**Comment by markdumay** [comment]
Wait, the latest build fails too… I’ll look into it. 

![image](https://github.com/gethinode/hinode/assets/61946753/08177978-9ced-406e-b118-194e5bba260e)

**Comment by myrthos** [comment]
What I take away from that is that you actually build on your phone 👏

**Comment by markdumay** [comment]
> What I take away from that is that you actually build on your phone 👏

It's actually a screenshot of the GH runner taken on my phone. I'm not that advanced yet... :-)

It looks like a known [issue](https://stackoverflow.com/a/64570109). I kind of remember I encountered a similar issue last year, but my memory isn't perfect anymore. ;-)

I'm adding `fsevents` to "optionalDependencies" in `package.json`, hopefully that resolves it once and for all. At least the current [build job](https://github.com/gethinode/hinode/actions/runs/5962818481/job/16174762820) is running fine again.  I'll push the change to a new release.

**Comment by markdumay** [comment]
It's pushed to [v0.18.7](https://github.com/gethinode/hinode/releases/tag/v0.18.7).

**Comment by myrthos** [comment]
Excellent, I will merge later today.

**Comment by markdumay** [comment]
It's a rather nasty issue it turns out. The main repo seems to work now, however, the template repo was quite persistent. In the end I had to revert back to `npm i` instead of `npm ci` for non-macOS. I'm leaving the main repo as-is for now, but let me know when you encounter any issues. Possibly I might need to adjust the `lint-build.yml` of this repo too. The reference is available here: https://github.com/gethinode/template/blob/main/.github/workflows/lint-build.yml

One more thing, you could revise the version to `*` in below section of `package.json`.

```json
  "optionalDependencies": {
    "fsevents": "*"
  },
```

**Comment by myrthos** [comment]
It works after the merge. If I then run `npm ci` I get no errors.

However, if after that I run `npm update` followed by `npm ci`, it generates the same error again. The json file is also changed because of the update.

There are two differences after the update.  
The first is that `"fsevents": "^2.3.3"` is moved from `optionalDependencies` to `devDependencies`  
The second is that in `"node_modules/fsevents"` the line `"dev": true` is added and the line `"optional": true` is removed.

There is also a version update of one of the dependencies, but that's not related.

**Comment by myrthos** [comment]
I can repair it by adding the line `"optional": true,` to `"node_modules/markdownlint-cli2/node_modules/fsevents"`.  
But it is not persistent. After an `npm update` it is gone again.

**Comment by myrthos** [comment]
Also `mod-update` fails, because it is also using `npm ci`.

**Comment by markdumay** [comment]
I have updated mod-update in the various repositories, it should now work cross-platform.
