### ISSUE TITLE
Enforce strict HTML rules supported by Goldmark renderer in safe mode

### ISSUE THREAD

**Issue by markdumay** [gethinode/hinode#468]
**Is your feature request related to a problem? Please describe.**
Release [v0.18.6](https://github.com/gethinode/hinode/releases/tag/v0.18.6) disabled unsafe HTML in the markdown processor by default. However, the related rule [MD033](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md033---inline-html) is not enforced by the markdown lint configuration yet.

**Describe the solution you'd like**
Enable rule MD033 for the markdown lint configuration and update the [contribution guidelines](https://gethinode.com/docs/getting-started/contribute/) accordingly.

**Describe alternatives you've considered**
Theme users may still opt to allow mixed content by changing their specific configuration. These adjustments include:
- Setting `unsafe` in [markup.goldmark.renderer] to `true`
- Setting `MD033` to `false` in `.markdownlint-cli2.jsonc`

**Additional context**
See discussion topic #466.

**Comment by markdumay** [comment]
It appears Hugo supports some HTML elements anyways. They are an extension to the [commonmark](https://commonmark.org) specification. Hugo uses the library [goldmark](https://github.com/yuin/goldmark/tree/master), which has built-in support for GitHub Flavored Markdown. The documentation does not include a formal definition of supported HTML elements and attributes, however, the logic seems implemented in the [HTML renderer](https://github.com/yuin/goldmark/blob/master/renderer/html/html.go).

It is suggested to extract the supported HTML elements from the HTML renderer only. These elements can then be input for a detailed configuration of [MD033](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md033---inline-html). The HTML renderer also specifies which exact attributes are allowed per supported HTML element, however, this seems unnecessary detailed for the rule configuration of markdown-lint.

**Comment by markdumay** [comment]
After some more testing, it appears Hugo does not allow any HTML in safe mode. The markdownlint configuration can be either on or off for MD033.

However, there is an issue with the example shortcode. The shortcode bypasses the markdown renderer and injects any input into the final rendered page.

**Comment by myrthos** [comment]
> After some more testing, it appears Hugo does not allow any HTML in safe mode. The markdownlint configuration can be either on or off for MD033.

That is good, but I would propose to still enable MD033. People would add HTML to markdown for a reason, so it is good that they are reminded by lint that it won't work.

**Comment by markdumay** [comment]
> That is good, but I would propose to still enable MD033. People would add HTML to markdown for a reason, so it is good that they are reminded by lint that it won't work.

Yes, I agree. I did find another security concern though. The `.Inner` property of a shortcode gives full access to the raw input. You can process that with `.Inner | .Page.RenderString` to use the (safe) Goldmark renderer. However, this does **not** work when using embedded shortcodes. The embedded shortcodes are processed first; the parent only has access to the processed output. You are forced to use `.Inner` directly in the parent shortcode. However, you can then inject **any input** into the parent.

**Comment by myrthos** [comment]
`.Page.RenderString` is capable of processing shortcodes, since version 0.100. So, why would `.Inner | .Page.RenderString` in the parent not work to process that embedded shortcode and its output?

**Comment by markdumay** [comment]
The children output HTML, which is then processed by the parent (in that order). You would call `.Page.RenderString` on HTML output, which will not work.

I created a demonstration and possible workaround in the [Hugo community](https://discourse.gohugo.io/t/using-nested-shortcodes-in-safe-mode/45897). But perhaps I'm overcomplicating things.

**Comment by myrthos** [comment]
I see. Changing `outer.html` to `.Inner | .Page.RenderString` would just change all HTML tags into plain text if HTML is not supported.

**Comment by myrthos** [comment]
Also, how would you know a shortcode is used as an outer, or as an inner for that matter. Unless you specifically write it to be used for that, would you not always use `.Inner | .Page.RenderString` and never just `.Inner`?
