### ISSUE TITLE
 [BUG] Image resource not available in thumbnail front matter

### ISSUE THREAD

**Issue by Giom-fm** [gethinode/hinode#483]
**Describe the bug**
I would like to bundle my articles with my assets (image in this case).
But the image resource from the page bundle can not be used for thumbnail in front matter.

**To reproduce**
1. Create a Page bundle
```
├── einsatz1
│  ├── img.jpg
│  └── index.md
```
2. index.md:
```
---
title: Title
resources:
- name: img
  src: baum2.jpg
thumbnail: 
    url: img
---
{{< image src="img" caption="Image caption" >}}
```
3. Warning is showed:
`WARN  Cannot find image resource: "img"`

**Expected behavior**
Like in the content section (which is working) I would like to use my image resource in the front matter. 
Reading the partials/assets/images.html docs saying `Else, the url is matched with a page resource and site asset (in that order)` it should be possible right?

**Log file**
If applicable, add a copy of Hugo's log messages.

**Screenshots**

**Environment (please complete the following information):**
 - Hinode version: v0.18.7
 - Host OS: debian unstable
 - Node version: v18.13.0
 - Hugo version: [hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended linux/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=gohugoio]
 - Browser: [Mozilla Firefox 116.0]

**Additional context**

**Comment by markdumay** [comment]
I don't believe what you have in mind is permitted by Hugo. The thumbnail of a page should be addressable outside of the local context, as it is being used by list pages and section lists (such as the homepage). In your setup, the thumbnail is only available to the local page. See the [hugo docs](https://gohugo.io/content-management/page-resources/) for more information.

I'll add a note to the Hinode docs to clarify the thumbnail expectations.

**Comment by Giom-fm** [comment]
I see. so I misunderstood it.

Thank you!
