### ISSUE TITLE
Upgrade v0.18.5 => v0.18.7 breaks building the site

### ISSUE THREAD

**Issue by Metisweb** [gethinode/hinode#487]
Today I upgraded version 0.18.5 to version 0.18.7
Upgrade process went okay.

Building the site in development with: npm run start throws an error. see below.

Error: error building site: 
render: failed to render pages: render of "page" failed: "/xxx/my-hinode-site-2/_vendor/github.com/gethinode/hinode/layouts/_default/single.html:160:23": execute of template failed: template: _default/single.html:160:23: executing "main" at <partial "partials/body.html" .>: error calling partial: execute of template failed: template: _default/single.html:87:7: executing "partials/body.html" at <partial "utilities/ProcessContent" (dict "page" .Page "raw" .RawContent)>: error calling partial: "/xxx/my-hinode-site-2/_vendor/github.com/gethinode/hinode/layouts/partials/utilities/ProcessContent.html:12:27": execute of template failed: template: partials/utilities/ProcessContent.html:12:27: executing "partials/utilities/ProcessContent.html" at <$page.RenderString>: error calling RenderString: "/xxx/my-hinode-site-2/content/en/blog/bootstrap-elements.md:93:64": failed to render shortcode "example": failed to process shortcode: "/xxx/my-hinode-site-2/_vendor/github.com/gethinode/hinode/layouts/shortcodes/example.html:24:49": execute of template failed: template: shortcodes/example.html:24:49: executing "shortcodes/example.html" at <.Page.RenderString>: error calling RenderString: "/xxx/my-hinode-site-2/content/en/blog/bootstrap-elements.md:1:1": failed to extract shortcode: shortcode "card" must be closed or self-closed

Before the upgrade the whole site worked as expected.

How could this issue be fixed?

Many thanks

Ton

**Comment by markdumay** [comment]
Release v0.18.6 introduced a refinement to the [card](https://gethinode.com/docs/components/card/). The card now supports inner content too. As a result, the card shortcode must be closed or self-closed.

**Old**

```markdown
{{< card >}}
```

**New**

```markdown
{{< card />}}
{{< card >}}Some content{{< /card >}}
```

**Comment by Metisweb** [comment]
Yep, that was indeed the issue. 
I have self-closed the card shortcode called on the bootstrap-elements.md page.

Mark, many thanks for the pointer and even more thanks for providing such a great template!

Dankjewel !!!!
