### ISSUE TITLE
[BUG] Spacing Issue: Lack of Space Between Shortcode Tooltip and Text Content

### ISSUE THREAD

**Issue by aefly** [gethinode/hinode#501]
**Describe the bug**
The bug involves a spacing issue that occurs when using a custom Hugo shortcode to generate a tooltip with a link. Specifically, when the shortcode is used to create a tooltip around a piece of text, such as "Tooltip," followed by other content, there is an unexpected lack of space between the tooltip and the subsequent text content.

**To reproduce**
1. Go to Tooltip content in [demo.gethinode.com](https://demo.gethinode.com/en/blog/bootstrap-elements/#tooltip)
2. See the lack of space

**Expected behavior**
Add space between Tooltip shortcode and text content

**Screenshots**
![en](https://github.com/gethinode/hinode/assets/127992938/4bb2489a-b5f0-49f9-b51b-7ce9a74507e2)
![fr](https://github.com/gethinode/hinode/assets/127992938/43579446-bd74-4bbf-841f-66361482f13a)

**Comment by markdumay** [comment]
Noted. It's actually a bigger problem, as this applies to multiple elements. Somehow there's a difference between development and production (deployed on Netlify).

**Comment by markdumay** [comment]
I found a way to recreate this locally. Add `--minify` to the `hugo server` command and visit the local website.

The html minification removes all redundant whitespace. Unfortunately, it has as side effect that inline elements do no longer have any spacing. Probably a `&nbsp;` character will fix this. I'll give it some more thought.

**Comment by markdumay** [comment]
I'm adding a `&nbsp;` character for the below elements by default. Setting the argument `spacing` to `false` will prevent this behavior.

- button
- icon (part of `mod-fontawesome`)
