### ISSUE TITLE
[Feature Request] Dark mode

### ISSUE THREAD

**Issue by rimatech987** [gethinode/hinode#57]
Hi Mark,
It would be nice to have dark mode for this theme (like in **Blist**) where you can switch from the default theme to dark mode via a toggle.
Is there a possibility to have this feature? 

Thank you!

**Comment by markdumay** [comment]
I agree it's a nice feature. Unfortunately It's not natively supported by Bootstrap yet, although it seems to be included in the upcoming release v5.3. See this [PR](https://github.com/twbs/bootstrap/pull/35857) for more details.

I'm hesitant to include a workaround right now, especially with native Bootstrap support around the corner. However, you might want to take a look at the example from [Frontendshape](https://frontendshape.com/post/bootstrap-5-dark-mode-example) if you're interested in such a workaround. Another approach worth looking into is this [answer](https://stackoverflow.com/a/63087710) at StackOverflow.

I'll keep this feature request open for now. I'll definitely add dark mode support once Bootstrap v5.3 is released.

**Comment by markdumay** [comment]
I released an alpha2 version just now. Hope you like it! Feedback is welcome.

**Comment by markdumay** [comment]
After a few revisions, release `v0.9.0` should be stable now.

**Comment by rimatech987** [comment]
Awesome mark. Thank you for keeping this wonderful theme up to date
