### ISSUE TITLE
[BUG]when I replace the content/_index.md, the home page only display the title content, without the description text.

### ISSUE THREAD

**Issue by AllenYangs** [gethinode/hinode#598]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Log file**
If applicable, add a copy of Hugo's log messages.

**Screenshots**

**Environment (please complete the following information):**
 - Hinode version: [e.g. v0.11.3]
 - Host OS: [e.g. macOS Ventura 13.3]
 - Node version: [e.g. node v18.15.0]
 - Hugo version: [e.g. hugo v0.109.0-47b12b83e636224e5e601813ff3e6790c191e371+extended darwin/amd64 BuildDate=2022-12-23T10:38:11Z VendorInfo=gohugoio]
 - Browser: [e.g. Google Chrome Version 108.0.5359.124 (Official Build) (arm64)]

**Additional context**

**Comment by AllenYangs** [comment]
http://www.tkiz.top/   wish someone could show me how to resolve it

**Comment by markdumay** [comment]
When submitting a bug, would you mind filling in the template? It's kind of difficult to reproduce the error without any context.

As a first thought, have you tried the latest beta version of Hinode? The generation of list pages and single pages is being revised, which might solve your problem.

**Comment by AllenYangs** [comment]
I am sorry I am a beginner to github issue.   

Hugo version : v0.117.0 , use the hinode theme  by 

echo "[[module.imports]]\npath = 'github.com/gethinode/hinode'" >> hugo.toml.

then I copied the   hinode/content/_index.md   to  SITE_DIR/content/     , and modified the text . 
So this situation occurred.

**Comment by markdumay** [comment]
No worries, I was able to reproduce your issue with the additional context. The rendering of the homepage is being revised. The latest stable version of Hinode `v0.20.7` ignores the `description` provided in the frontmatter. Instead, you can type your content directly below the final `---`. The following example illustrates this:

```markdown
---
title: Welcome to Hinode!
thumbnail: /img/sunrise.jpg
---

Add your feature content here.
```

The beta release of Hinode (currently [v0.21.0-beta9](https://github.com/gethinode/hinode/releases/tag/v0.21.0-beta9)) **does** use the description field. You can use this version by replacing the Hinode version in `go.mod`:

``` go
github.com/gethinode/hinode v0.21.0-beta9 // indirect
```

Run `hugo mod get -u` to download the updated modules. Now you can use the original input:

``` markdown
---
title: Welcome to Hinode!
description: Add your feature content here.
thumbnail: /img/sunrise.jpg
actions:
  get-started:
    url: "https://gethinode.com/docs"
    title: "Get started"
    icon: "fas book-open"
---

```

**Comment by AllenYangs** [comment]
oh ,I see.  The problem has been solved !  

Hinode is  really the most beautiful theme on Hugo. I will  continue to learn it and use it more often. Thank you a lot to create it !
