### ISSUE TITLE
[BUG] Nested section not working after upgrade 20.7 -> 21.7

### ISSUE THREAD

**Issue by giomf** [gethinode/hinode#633]
**Describe the bug**
I have a content folder that looks like this:
```
einsaetze/
├── 2022
│   ├── 0000
│   │   ├── img
│   │   │   ├── IMG_2028.jpg
│   │   │   ├── IMG_2036b.jpg
│   │   │   ├── IMG_2082_2.jpg
│   │   │   └── IMG_2145_2.jpg
│   │   └── index.md
│   ├── 0001
│   │   ├── img
│   │   │   ├── 2022-0001-1.jpg
│   │   │   ├── 2023-0001-2.jpg
│   │   │   └── 2023-0001-3.jpg
│   │   └── index.md
│   ├── 0002
│   │   ├── img
│   │   │   ├── photo_2022-02-06_20-36-30.jpg
│   │   │   ├── photo_2022-02-06_20-36-33.jpg
│   │   │   └── photo_2022-02-06_20-36-52.jpg
│   │   └── index.md
│   ├── 0003
│   │   ├── img
│   │   │   ├── orkan_feb_1.jpg
│   │   │   ├── orkan_feb_2.jpg
│   │   │   ├── orkan_feb_3.jpg
│   │   │   └── orkan_feb_4.jpg
│   │   └── index.md
│   └── _index.md
├── 2023
│   ├── 0000
│   │   ├── img
│   │   │   └── 2023-0000-1.jpg
│   │   └── index.md
│   ├── 0001
│   │   ├── img
│   │   │   ├── 2023-0001-1.jpg
│   │   │   ├── 2023-0001-2.jpg
│   │   │   └── 2023-0001-3.jpg
│   │   └── index.md
│   ├── 0002
│   │   ├── img
│   │   │   ├── 2023-0002-1.jpg
│   │   │   ├── 2023-0002-2.jpg
│   │   │   └── 2023-0002-3.jpg
│   │   └── index.md
│   ├── 0003
│   │   ├── img
│   │   │   ├── 2023-0003-1.jpg
│   │   │   ├── 2023-0003-2.jpg
│   │   │   ├── 2023-0003-3.jpg
│   │   │   └── 2023-0003-4.jpg
│   │   └── index.md
│   └── _index.md
└── _index.md
```
Before the update I was able to navigate to `<domain>/einseatze` and saw all pages listed in order of their timestamp.
Now unfortunately I see two cards named "2022" and "2023". I know about the [nested](https://gethinode.com/docs/configuration/layout/) configuration parameter which is enabled by default.

**To reproduce**
1. Create a nested structure and serve it with hinode 20.7
2. Update to hinode 21.7
3. Serve the site again
4. See the two cards instead of all available cards in the nested structure

**Expected behavior**
All pages should be listed in the top level listpage,

**Log file**
-

**Screenshots**
-

**Environment (please complete the following information):**
 - Hinode version: 21.7
 - Host OS: nixos-unstable
 - Node version: -
 - Hugo version: hugo v0.120.3+extended linux/amd64 BuildDate=unknown VendorInfo=nixpkgs
 - Browser:Mozilla Firefox 119.0

**Additional context**
-

**Comment by markdumay** [comment]
I suspect this is an unwanted side-effect of the changes introduced by release v0.21.6 (see discussion https://github.com/gethinode/hinode/discussions/617). 

I'll look into it. To speed up the investigation, could you perhaps share a (minimal) repository that demonstrates / reproduces the issue?

**Comment by giomf** [comment]
Sure here is the repository: https://github.com/giomf/hinode-debug

* When I use version v0.20.7 its working.
* When upgrading to v0.21.0 no content is shown at all.
* When upgrading to v0.21.08 the content is shown again but only the top level cards.

**Comment by markdumay** [comment]
Thanks for sharing the example. I revised the code in new branch `nested`, care to test it? @dims31, perhaps you also might want to take a look?

```sh
git clone -b nested https://github.com/gethinode/hinode.git hinode-nested
```

In the revised setup, you can still specify `nested` at `section` level. For example, you can define the behavior for the `test_content` section in `params.toml`.

```toml
[sections]
    [sections.test_content]
        nested = true # default value
```

The `nested` behavior applies to the entire section, including any child branches. You can override this behavior by adding  `nested` to the frontmatter of an individual page. For example, the following configuration will render `A` and `B` only when added to `content/test_content/_index.md`.

```yaml
---
title: Test content
nested: true
---
```

**Comment by giomf** [comment]
I just tested it and it seems to work.
Maybe its just me but it the term _default value_ is a little misleading because you still have to create the section and set `nested = true` or set `nested: true` in the frontmatter to work.
I thought that default value means it just work out of the box without any additionally config.

So for my usecase I still need to create the section with:
```
[sections]
    [sections.test_content]
         nested = true
```

**Comment by markdumay** [comment]
Thanks for your review. I fixed the default behavior and submitted the change to the `nested` branch. Care to do a final review before I merge it with the main branch?

**Comment by giomf** [comment]
Thanks! the default behavior works great now.
But I encounter another problem.

**Comment by giomf** [comment]
I Just tested it an it works now.
Thank you!
