### ISSUE TITLE
[BUG] meta description isn't truncated at 160 characters

### ISSUE THREAD

**Issue by elsingaa** [gethinode/hinode#719]
**Describe the bug**
The meta description is not truncated after 160 characters. Microsoft Bing and other SEO-sensitive sites treats that as an error.

**To reproduce**
1. Create a post with more than 160 characters in text
2. generate the site
3. view source of genereated post and look for: meta name="description" content=
4. count the characters (e.g. use https://www.charactercountonline.com)

**Expected behavior**
Expected that the meta description is truncated at 160 characters

**Log file**
not applicable.

**Screenshots**
<img width="982" alt="Screenshot 2024-01-14 at 20 49 37" src="https://github.com/gethinode/hinode/assets/859598/e42bd256-6905-4990-b2b3-8a031850ee70">

**Environment (please complete the following information):**
 - Hinode version: [e.g. v0.22.3]
 - Host OS:  macOS Sonoma 14.1.2
 - Node version: node v20.5.1
 - Hugo version: hugo v0.121.2-6d5b44305eaa9d0a157946492a6f319da38de154+extended darwin/arm64 BuildDate=2024-01-05T12:21:15Z VendorInfo=brew
 - Browser: Safari 17.1.2 (19616.2.9.11.12)

**Additional context**
I know it is better to have a handwritten description/summary, but since I don't have them for all articles, I would like to have it truncated.

The strange thing is that in `layouts/partials/head/head.html` description is truncated to 150 characters, but for some reason `layouts/partials/head/seo.html` doesn't use that truncated description.

As a workaround I edited seo.html and changed the line from
`{{ $description := or (partial "utilities/GetDescription.html" .) .Site.Params.main.description  }}`
to

`{{ $description := or (partial "utilities/GetDescription.html" .) .Site.Params.main.description | truncate 160 }}`

since 160 is the maximum advised. That way it will also be used for the

**Comment by markdumay** [comment]
Thanks for spotting this! I released a fix in[ v0.22.4](https://github.com/gethinode/hinode/releases/tag/v0.22.4). I also improved the description itself. The revised version should no longer include HTML escape characters. See this [commit](https://github.com/gethinode/mod-utils/commit/8333207e6602e72886d01118e5bb9db1f7b15d3b) for more details.
