### ISSUE TITLE
[BUG] Section list content is rendered incorrectly in small viewports

### ISSUE THREAD

**Issue by doganulus** [gethinode/hinode#728]
**Describe the bug**
Section list content is rendered incorrectly in small viewports.
- HTML lists are broken 
- Non-ASCII characters are not rendered

**Expected behavior**
The section list content should be rendered correctly in small viewports like larger viewports.

**Screenshots**
Check the homepage https://bouncmpe.github.io/rv24/ and reduce the window size.

**Environment:**
 - Hinode version: v0.22.3

**Comment by markdumay** [comment]
Can you share a bit more details about your environment, specifically the browser you are using? I've tested your site on Firefox 121.0.1 (64-bit, Windows) and Chrome v20.0.6099.225 (64-bit, Windows) and can't reproduce the errors. Perhaps you could share a screenshot that illustrates the issues too?

**Comment by doganulus** [comment]
This is the incorrect rendering for small screens.
<img src="https://github.com/gethinode/hinode/assets/1174212/0614d514-dec6-403d-9531-380653918d9b" width="300">

No problem with large screens.
<img src="https://github.com/gethinode/hinode/assets/1174212/f5447bed-b66f-4c6c-b722-f394899b9b21" width="400">

The problem exists on Firefox 121.0.1 and Chrome v120.0.6099.129 on OpenSUSE Tumbleweed, Firefox and Chrome on Windows, and the latest Safari and Chrome on iOS.

**Comment by markdumay** [comment]
Got it, thanks for the clarification! I'll look into it.

**Comment by doganulus** [comment]
Thanks! It is fixed for the list layout. 

I noticed the same problem occurs for the card layout too. Here is the screenshot:
![hinode-bug-2](https://github.com/gethinode/hinode/assets/1174212/644fbf10-33fa-4246-980f-69f464377325)

**Comment by markdumay** [comment]
You can now adjust the filter to allow special characters to pass. Adding the following filter would keep Turkish diacritics in card descriptions (add to `params.toml`):

```toml
[modules]
    [modules.utils]
        filter = "[^0-9A-Za-zŽžÀ-ÿ\u011E\u011F\u0130\u0131\u015E\u015F ;.,\\/'’\"]"
```

I'm hesitant to adjust the card descriptions though. They are primarily used for blog post summaries. As a result, they render "plain" text only. You could override the card rendering if needed.
