### ISSUE TITLE
Error: command error: failed to load config: 

### ISSUE THREAD

**Issue by heihahehe** [gethinode/hinode#738]
I installed this template using "hugo" and reported errors when allowed.
"D:\hugo\seayo\my-hinode-site\hugo.toml:1:1": unmarshal failed: toml: invalid character at start of key: ÿ

![20240129154807](https://github.com/gethinode/hinode/assets/152707762/4f549df7-d509-4320-8741-e135d10460d2)
![20240129154820](https://github.com/gethinode/hinode/assets/152707762/bc77e9e7-cc97-49d4-a162-8161995a548c)

**Comment by markdumay** [comment]
The installation commands for using Hugo were not fully compatible with Windows. I've revised the [documentation](https://gethinode.com/docs/getting-started/introduction/).

I you replace `\n` with a newline character, your Hinode site should work properly.

**Comment by heihahehe** [comment]
Thanks, I was able to use PowerShell 7.4 to execute commands.
