### ISSUE TITLE
[BUG] Docs: Typo in `config/default/` references

### ISSUE THREAD

**Issue by ckamps** [gethinode/hinode#779]
**Describe the bug**
 
In the [Managed links](https://gethinode.com/docs/content/links-and-cross-references/#managed-links) doc, there are several references to `config/default/params.toml` that I believe should be `config/_default/params.toml` - missing underscore before `default`.

![image](https://github.com/gethinode/hinode/assets/1332810/30926575-495c-40ea-a1be-d93792b174e8)

**To reproduce**

See the doc reference.

**Expected behavior**

Accurate path references.

**Log file**

NA

**Environment (please complete the following information):**
 - Hinode web site

**Comment by markdumay** [comment]
Thanks for spotting this! Is has been fixed in https://github.com/gethinode/docs/pull/319.
