### ISSUE TITLE
Add possibility to disable thumbnail scaling

### ISSUE THREAD

**Issue by hawkeye116477** [gethinode/hinode#831]
## Problem or enhancement idea

I'd like to include just static images to blog without processing them, cuz some of them look worse after that.

## Proposed solution

Add to config or markdown a way to disable thumbnail scalling, processing, to just include them from /static folder.

## Alternatives

-

## Additional context

-

**Comment by markdumay** [comment]
Release [v0.24.0](https://github.com/gethinode/hinode/releases/tag/v0.24.0) introduces a new argument called `plain` to [bypass all image transformations](https://gethinode.com/docs/components/image/#arguments). In addition, I've included an increased resolution of 2800 pixels wide to better cater for high-resolution displays. You can customize the supported dimensions by modifying the [data/dimensions.yml](https://github.com/gethinode/hinode/blob/main/data/dimensions.yml) file.

**Comment by lgwapnitsky** [comment]
this works great for the shortcode, but what about for thumbnails in the frontmatter?
