### ISSUE TITLE
[BUG] Break optional scripts

### ISSUE THREAD

**Issue by doganulus** [gethinode/hinode#853]
## Describe the bug

The switch from v0.22 to v0.23 breaks the `partials/optional-scripts` partial. 

## Expected behavior

I would like to add an optional script at the end of a page by overriding `partials/optional-scripts.html`.

## Host environment

 - Hinode version: v0.23.3

## Additional context

The optional script has been used to add `mermaid` functionality to a page.

**Comment by markdumay** [comment]
When submitting a bug, it's helpful to capture the precise error logs, host environment, etc. The bug template contains several sections to consider. Also, please review the following guidelines:

> When submitting a bug, please include the exact steps to reproduce the issue. Ideally, use a minimal repo created with the Hinode installation steps for either Hugo or npm (https://gethinode.com/docs/getting-started/introduction/#installation). Add any additional commands and configuration adjustments from there on.

In addition, the latest version of Hinode is [v0.23.3](https://github.com/gethinode/hinode/releases/tag/v0.23.3). Which exact version is causing the issue?

**Comment by doganulus** [comment]
Fixed version info as `0.23.3`

This commit https://github.com/gethinode/hinode/commit/7ecc818ca18a00e32bcfb022922a0e98aa41621c refactors `partials/optional-scripts` to `footer/optional-scripts`, which I was overriding to add `mermaid` script at the end of the page. 

It is better to continue supporting `partials/optional-scripts` as a means to add custom user-defined scripts.

**Comment by markdumay** [comment]
Thanks for the clarification. You're of course free to adapt the Hinode theme in any you want, however, overriding the undocumented `optional-scripts` file is not endorsed or supported. You might want to consider the guide on how to [develop custom modules compatible with Hinode](https://gethinode.com/guides/modules/). Alternatively, you can move your custom partial to the new location.
