### ISSUE TITLE
[BUG] proper format for the search bar

### ISSUE THREAD

**Issue by alkock** [gethinode/hinode#875]
## Describe the bug

if you use the search bar, it occurs under certain system conditions that texts are not displayed completely. 

## To reproduce

Using a placeholder text >20 characters in the search bar.

## Expected behavior

The text should be shown properly in full size

## Screenshots

This is the demowebsite using the text: 'This is a Text that is very long' (32 chars)
<img width="1429" alt="image" src="https://github.com/gethinode/hinode/assets/18499444/171c92b1-bdbc-4441-8ad4-f76486377419">

## Host environment

Please complete the following information where applicable.

 - Hinode version: 0.23.6
 - Host OS: macOS Sonoma 14.4.1 on 13,3" (2560px x 1600px)
 - Node version:  v18.20.0
 - Browser: Google Chrome 123.0.6312.107 (Official Build) (arm64)

## Additional context

The problem is extracted [here](https://github.com/giomf/ff-eppendorf-website/issues/7#issuecomment-2049241502)
The problem occurs in production [here](https://ff-eppendorf.de/)

**Comment by markdumay** [comment]
I have revised the underlying behavior of the search input in Hinode [v0.23.8](https://github.com/gethinode/hinode/releases/tag/v0.23.8). By default, the `max-width` of the search input is set to `20rem`. You can now override this setting by adding the following code to `assets/scss/theme/theme.scss`:


```sass
@include media-breakpoint-up(md) {
    .search {
        // use unset to fill up all available space
        // max-width: unset !important;
        // override max-width to any size
        max-width: 30rem !important;
    }
}
```

**Comment by markdumay** [comment]
Release [v0.23.9](https://github.com/gethinode/hinode/releases/tag/v0.23.9) removes some unwanted vertical margins around the search input.

**Comment by alkock** [comment]
That works, Thank you!
