### ISSUE TITLE
Pagination works only in the homepage [BUG]

### ISSUE THREAD

**Issue by anapaulagomes** [gethinode/hinode#910]
## Describe the bug

First of all, thanks for your help and for this great theme!

The `paginate` param only works in the homepage. When the user clicks on "More", it goes to a page with all posts with no pagination.

I'm not sure if this is a bug or a configuration that I'm missing but even after changing the layout to cards and play with the params on the section, I couldn't get this to work.

## To reproduce

1. Create a new website following the instructions https://gethinode.com/docs/getting-started/introduction/#installation
2. Add to the `content` directory a `_index.md` file and create a directory called `dogs` with 10 posts inside (ideally with `draft=false`).
3. Run `hugo server`. You should see the home page and all posts as follow:

<img width="906" alt="print1" src="https://github.com/gethinode/hinode/assets/1899950/38fe719d-04b0-48dc-92cc-7b2e6e83ce5d">
<img width="749" alt="print2" src="https://github.com/gethinode/hinode/assets/1899950/d0829dae-0205-4b54-b589-85b8a2dc6020">

*For the example in the screenshot, I've generated 25 posts.

## Expected behavior

By default, the `paginate` param is set to 9. And this is respected in the front page.
I expected that the http://localhost:1313/dogs/ page would display two pages ([1], [2]), one with 9 posts and another one with one post.

## Host environment

 - Hinode version: v0.23.11
 - Host OS: Windows 11
 - Node version: [e.g. node v18.15.0]
 - Browser: Firefox 125.0.2 (64-bits)

## Hugo environment

Copy the output of `hugo env` or `npm run env` here.

```bash
hugo v0.124.1-db083b05f16c945fec04f745f0ca8640560cf1ec+extended linux/amd64 BuildDate=2024-03-20T11:40:10Z VendorInfo=gohugoio
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.22.1"
OptionParser::InvalidOption: invalid option: --embedded
  Use --trace for backtrace.
github.com/sass/libsass="3.6.5"
github.com/webmproject/libwebp="v1.3.2"
```

## Additional context

I'm terrible with frontend, so bear with me. :)

**Comment by markdumay** [comment]
Thanks for spotting this @anapaulagomes! This [commit](https://github.com/gethinode/hinode/commit/d5b8e6af8bfb9e2eafe80314243a5ef37859cf8c) introduced an unwanted side effect. I will release a fix soon.

**Comment by markdumay** [comment]
The fix is addressed in release [v0.23.12](https://github.com/gethinode/hinode/releases/tag/v0.23.12).

**Comment by anapaulagomes** [comment]
Hi @markdumay! Thanks a lot for the fast reply. The change worked for the site I created for this issue example but not for my own website. I believe that it is because the sections configuration are different and not all use the card-groups. Does it make sense? Below the configurations:

```
[sections]
    [sections.one]
        title = "One"
        sort = "date"
        reverse = true
        cols = 3
        color = ""
        padding = "0"
        header = "tags"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom card-body-margin"
        homepage = 6
        separator = true
        nested = true
    [sections.blog]
        title = "Blog"
        sort = "date"
        reverse = true
        cols = 1
        background = "body-tertiary"
        color = "body"
        padding = "3"
        header = "none"
        footer = "tags"
        orientation = "horizontal"
        style = "border-1 card-emphasize"
        homepage = 3
        separator = false
```

I appreciate your help.

**Comment by markdumay** [comment]
That's weird, as your configuration seems to use the default `layout` type for both `one` and `blog`. I tested your section configuration with the Hinode example site, and it seems to work as expected. Could you perhaps share the steps how to reproduce this, or share a (minimal) test repo that illustrates the issue?

**Comment by anapaulagomes** [comment]
I'll do it over the week! Thanks a lot Mark.

**Comment by anapaulagomes** [comment]
Hi @markdumay, I've checked the example I created with the configuration and the content from my website and the pagination worked. I still have to look further to investigate why is not working, so I think you can consider the issue fixed. Thank you so much for looking into this!

**Comment by anapaulagomes** [comment]
After I updated the modules and deleted the vendor directory (?), it is working. Thanks lot! 🏆
