### ISSUE TITLE
[BUG] Reduce screen flickering in color mode

### ISSUE THREAD

**Issue by markdumay** [gethinode/hinode#981]
## Describe the bug

In dark mode, Hinode briefly shows a light color mode when loading a new page.

## To reproduce

1. Visit Hinode's demo site in dark mode.
2. Click on random pages
3. See the white flash when pages load

## Host environment

Please complete the following information where applicable.

 - Hinode version: [v0.24.0] and later

## Additional context

The screen flickering is an unwanted side-effect of https://github.com/gethinode/hinode/pull/972.

**Comment by markdumay** [comment]
@TommyTran732 [release v0.25.4](https://github.com/gethinode/hinode/releases/tag/v0.25.4) should be an improvement. Although not 100% eliminated on all pages, the screen flickering should be much less than before. Feel free to share your feedback!

**Comment by TommyTran732** [comment]
It is significantly better. I don't even see the screen flicking anymore, except for the navbar problem mentioned in #1083
